CHANGES.txt
pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py

[See line 137 of the split_editor_area_pane and line 245 of the unit test file for the important changes.]
When a tab is created with the splitEditorAreaPane, the index variable in the `add_editor` method was wrong only for the first editor. That led to the tooltip for that editor being lost. This is a hack to fix that. The real fix is probably down inside qt or pyside...
Thanks to @corranwebster for his help tracking this one!

Tab index bug fix

---

pyface/ui/wx/window.py

The wx event handler for EVT_ACTIVATE needs the call to event.Skip() to allow the Mac menubar to be changed when switching among top level windows.
I have an example of the problem but it depends on the work I've been doing on adding wx support for tasks...
Anyway, for reference, see http://www.wxpython.org/docs/api/wx.ActivateEvent-class.html :
>Please note that usually you should call event.Skip() in your handlers for these events so the default handlers will still be called, as not doing so can result in strange effects.

Call event.Skip() in _wx_on_activate to allow Mac menubar to change

---

.travis.yml
README.rst
pyface/__init__.py
pyface/tests/test_toolkit.py
pyface/toolkit.py
pyface/ui/null/tests/bad_import.py
pyface/ui/qt4/python_editor.py
pyface/ui/qt4/tests/bad_import.py
pyface/ui/wx/tests/bad_import.py

There was an import error in the Qt implementation of the `PythonEditor` that was being silently swallowed, which meant that the `PythonEditor` widget was unavailable in Qt4.  This PR:
* fixes that particular issue
* modifies the toolkit import mechanism so that it only swallows import errors for the module that we are trying to import
* adds pygments to the travis.yml as import errors around pygments were also being swallowed silently
The latter means that import errors like the original one will make `import pyface.api` fail very quickly and should be noticed in CI.

Fix Qt4 python editor imports and toolkit import mechanism

---

README.rst
docs/source/index.rst
pyface/toolkit.py

Unfortunately, can't easily test this because `_init_toolkit()` pulls the ladder up after itself, so we can't reset the toolkit to test the code.

Deprecate wx toolkit default

---

pyface/ui/qt4/tasks/main_window_layout.py
pyface/ui/qt4/tasks/task_window_backend.py

The layout callback run by the following code https://github.com/enthought/pyface/blob/master/pyface/ui/qt4/tasks/main_window_layout.py#L129 can run after the tasks control has been destroyed.
This PR resolves the issue by flagging that the control is about to be destroyed from the TaskWindow backend implementation by setting the control to `None`.  The layout can then check this and not do any further work.

Fix task window layout running after control destroyed

---

travis-ci-requirements.txt

I think this happened in the move from `dev_requirements.txt` to `travis-ci-requirements.txt`.

Fix regression on traitsui branch used in CI

---

pyface/grid/api.py
pyface/grid/checkbox_image_renderer.py
pyface/grid/checkbox_renderer.py
pyface/grid/combobox_focus_handler.py
pyface/grid/composite_grid_model.py
pyface/grid/edit_image_renderer.py
pyface/grid/edit_renderer.py
pyface/grid/grid.py
pyface/grid/grid_cell_image_renderer.py
pyface/grid/grid_cell_renderer.py
pyface/grid/grid_model.py
pyface/grid/inverted_grid_model.py
pyface/grid/mapped_grid_cell_image_renderer.py
pyface/grid/simple_grid_model.py
pyface/grid/trait_grid_cell_adapter.py
pyface/grid/trait_grid_model.py
pyface/wx/clipboard.py

Fixes #165 
Global search-and-replace on untested, deprecated code.  Fun, hopefully it works :)

Remove usage of logging.warn in favour of logger.warning.

---

README.rst
docs/source/index.rst
pyface/toolkit.py

This switches the lookup order for 'wx' and 'qt4' when no toolkit has been explicitly specified.  This may affect users who have both libraries installed and who have not specified the toolkit to use via environment variables or other methods.

Make qt4 the default toolkit

---

pyface/ui/qt4/code_editor/code_widget.py
pyface/ui/qt4/progress_dialog.py
pyface/ui/wx/progress_dialog.py

The first commit fixes QT and WX ProgressDialog to enable updates to the message which did not work.
The second commit adds a "focus_lost" signal in the QT CodeWidget that is emitted whenever focus goes out of the widget, thus enabling traitsui CodeEditor to behave properly for auto_set=False (see other pull request on traitsui)

A small fix to ProgressDialog and a change to code_widget in order to enabe (auto_set=False) for traitsui Qt CodeEditor

---

pyface/ui/qt4/progress_dialog.py

When the number of steps in the progress dialog loop is large, the label text for the estimated and remaining times get prepended by the trailing digits of the previous step's labels, leading to hilarious results such as this:
With this fix in place, the same example results in this:
A minimal working example to reproduce this bug is below, and is a small modification of the [progress_dialog.py](https://github.com/enthought/pyface/blob/master/examples/progress_dialog.py) example.
```
#
#
from __future__ import print_function
import time
from pyface.api import GUI, ApplicationWindow, ProgressDialog
from pyface.action.api import Action, MenuManager, MenuBarManager
def task_func(t):
progress = ProgressDialog(title="progress", message="counting to %d"%t, max=t, show_time=True, …
```

FIX: bug in ProgressDialog timer labels

---

pyface/toolkit.py

Use a context manager to temporarily set the `ETSConfig.toolkit` when attempting to import a toolkit in the situation where it is not specified by other means.  This ensures coherence between Pyface, TraitsUI any any other library that uses `ETSConfig.toolkit` as a clue as to which backend to use.
This PR uses a context manager provided by `ETSConfig` when available, but if not there is a fallback avaialble.

Provisional toolkit selection

---

pyface/ui/qt4/tasks/dock_pane.py

On of the change handlers was using the `on_trait_change` decorator providing three separate trait names. However, this signature is not supported since (https://github.com/enthought/traits/pull/207) and actually never properly worked. Older versions of traits would ignore the second trait (not covered in the tests) and the recent version raises an error.
This PR fixes the issue for both old and new versions of traits

fix: correct the extened trait change description

---

pyface/ui/qt4/workbench/workbench_window_layout.py

The dock widget's ViewContainer instead of the main window should be passed for creating UI.

Qt4 Workbench should create UI with parent being the dock widget

---

pyface/ui/qt4/util/modal_dialog_tester.py
pyface/ui/qt4/util/tests/test_modal_dialog_tester.py

I needed to test if a dialog is indeed opened in many occasions.   The flag would be a nice thing to have.
@corranwebster flag does solve the problem!
My previous attempt failed because of some stupid mistake which leads to non-modal dialog being opened.

Add modal dialog_was_opened flag

---

pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py

This fixes #202. I've given up on writing a test, since I can't figure out how to set focus or set the active window from within a test method.

Update SplitEditorAreaPane.active_editor on focus changes

---

pyface/ui/qt4/workbench/tests/test_workbench_window_layout.py
pyface/ui/qt4/workbench/workbench_window_layout.py

Fixes behavior experienced in enthought/mayavi#321.
Performs a check before trying to set text color.

Fix exception when closing all tabs

---

pyface/ui/qt4/workbench/workbench_window_layout.py

Without this patch, starting Mayavi2 in python3 environment gives you the following error:
```
File "/Users/kit/Envs/mayavi-py3/bin/mayavi2", line 9, in <module>
load_entry_point('mayavi', 'gui_scripts', 'mayavi2')()
File "/Users/kit/ETS/mayavi/mayavi/scripts/mayavi2.py", line 650, in main
mayavi.main(sys.argv[1:])
File "/Users/kit/ETS/mayavi/mayavi/plugins/app.py", line 195, in main
app.run()
File "/Users/kit/ETS/mayavi/mayavi/plugins/mayavi_workbench_application.py", line 81, in run
window.open()
File "/Users/kit/ETS/pyface/build/lib/pyface/workbench/workbench_window.py", line 144, in open
self._create()
File "/Users/kit/ETS/pyface/build/lib/pyface/ui/qt4/application_window.py", line 121, in _create
contents = self._create_contents(self.control)
File …
```

Fix workbench_window_layout in python3

---

pyface/tasks/task_layout.py
pyface/tasks/tests/test_task_layout.py

LayoutContainer's __init__ accepts arguments *items and **traits. At first glance, the argument names make it seem as if one could initialize LayoutContainer.items by calling LayoutContainer(items=some_items). However, doing this would create a task layout with items=() and traits={'items': some_items}. 
This behavior is misleading. I ran into some code yesterday where a vsplitter had been constructed with VSplitter(items=list_of_items), and it took me a few looks to realize that {items: list_of_items} was being passed to **traits instead of items.
The current commit will not fix the above example, but I'm hoping it will make it clear that the above usage is incorrect. All of my ideas for making LayoutContainer(items=[...]) assign a value to items would break backwards compatibility. …

Clarified the purpose of LayoutContainer construction args.

---

pyface/ui/qt4/workbench/workbench_window_layout.py
pyface/ui/wx/workbench/workbench_window_layout.py
pyface/workbench/tests/test_workbench_window.py
pyface/workbench/user_perspective_manager.py
pyface/workbench/workbench_window.py

Fix https://github.com/enthought/mayavi/issues/337
Include the info whether the editor_area is visible in the `window_memento` file.  This code still respects old `window_memento` files and assume `show_editor_area = True` in that case.
The more difficult thing to write was the test case.  A lot of mock objects are required for testing this bug fix.

Fix restoring show_editor_area from saved perspective

---

appveyor.yml

Replace `--no-use-wheel` with `--no-binary :all:` in appveyor pip install.

Fix Appveyor tests

---

pyface/tasks/task_window.py
pyface/tasks/tests/test_task_window.py

Fixes #218.  Includes tests.  We now listen to `active_task.name` instead of just `active_task`.

Fix task window title

---

pyface/ui/wx/action/action_item.py
pyface/ui/wx/action/tool_bar_manager.py
pyface/ui/wx/application_window.py

Fixes #246. AUI windows must explicitly ask for an AUI toolbar; other code is adapted to the possibility of getting one or the other type.

Fix for toolbars in non-AUI windows

---

pyface/tasks/tests/test_enaml_dock_pane.py
pyface/tasks/tests/test_enaml_editor.py
pyface/tasks/tests/test_enaml_task_pane.py

unittest and haas don't understand a module-level `raise unittest.SkipTest`, and report an `ImportError` rather than a skip for each test method.

Replace module-level use of unittest.SkipTest with a class decorator.

---

pyface/ui/qt4/code_editor/tests/test_code_widget.py

The `setupClass` spelling is only appreciated by nose. `setUpClass` works for nose, unittest and haas. As far as I can tell, neither spelling is understood by pytest.

Fix nosetests-specific spelling of setUpClass.

---

pyface/ui/qt4/util/gui_test_assistant.py
pyface/ui/qt4/util/modal_dialog_tester.py
pyface/ui/qt4/util/tests/test_gui_test_assistant.py

This backports some fixes for the GuiTestAssistant to pyface.
- Avoid uncollectable garbage caused by events not being disconnected
- Avoid uncollectable garbage due to references held in `sys.last_traceback`
- Improve robustness by flushing Qt events and quitting the application on `tearDown`
- Correctly handle the case where no traits are waited for in an event loop
- Correctly handle the case where multiple traits are waited for in an event loop

Update gui test assistant

---

README.rst
pyface/__init__.py
setup.py

This improves the setup script in two ways:
- Avoid `pyface` imports in `setup.py`. Importing pyface when you don't have pyface installed, or when a different version is installed, can be problematic, particularly when working with non-git clones.
- Use extras_require to allow more specific installs.  In particular, we can specify gui backend requirements, and the fact that Workbench currently relies on traitsui.
This also removes Python 2.6 as officially supported, since Traits no longer supports 2.6.

Setup.py improvements

---

docs/source/index.rst
docs/source/toolkits.rst
pyface/base_toolkit.py
pyface/tests/test_new_toolkit/init.py
pyface/tests/test_new_toolkit/widget.py
pyface/tests/test_toolkit.py
pyface/toolkit.py
pyface/ui/null/init.py
pyface/ui/qt4/init.py
pyface/ui/wx/init.py
setup.py

This PR makes the toolkit selection mechanism a lot cleaner, clearer and more standard.  We use the `pkg_resources` mechanisms to look for `pyface.toolkit` entry points.  This allows third-party libraries to add new backends.  The core library provides entry points for `qt4`, `wx` and `null` backends.
We also provide a base class for the `toolkit_object` importers which allows multiple packages to be searched for backend implementations of toolkit objects.  This allows applications to more easily support custom widgets for multiple toolkits.

Allow plugin toolkits

---

README.rst

Redirect the appveyor build badge to EnthoughtOSS account

Fix badge in README

---

.travis.yml
tasks.py
travis_ci_bootstrap_edm.sh

Also reduce the number of Travis CI runs by combining backend tests, as done for TraitsUI tests.

Travis CI for Python 3.6

---

pyface/ui/qt4/util/gui_test_assistant.py

The `self.qt_app.quit()` call in `GuiTestAssistant.tearDown` was causing test interactions, and appears to be useless: as far as I can see, it only ever makes sense to call `quit` or `exit` from within the event loop, and if we're running the `tearDown` method from within the event loop then something's very wrong indeed.

Don't attempt to quit a QApplication from outside its event loop.

---

pyface/ui/wx/tasks/dock_pane.py
pyface/wx/aui.py

OK, for realz this time. The simple fix of the last pull request has issues on different platforms, so it require a little more code. It still prevents a time-consuming re-layout of the entire AUI manager, although it does refresh everything. Still much faster than a layout, though.

Fixed unnecessary full re-layout of AUI when only changing a pane's name

---

pyface/toolkit.py

This PR fixes https://travis-ci.org/enthought/traitsui/jobs/241017726#L2161 error seen when using python 3 and updates the logging so that stderr is not normally polluted with tracebacks

Update toolkit import code

---

pyface/ui/qt4/util/gui_test_assistant.py

This PR makes the unconditional `self.qt_app.closeAllWindows()` step in `GuiTestAssistant.tearDown` conditional on there being at least one top-level widget. This should reduce one potential cause of test interactions.
I've also added a garbage collection step; I've seen at least one application where the garbage collection was necessary for removing top-level widgets.

Only try a closeAllWindows if there's at least one top-level widget alive.

---

pyface/ui/qt4/util/gui_test_assistant.py

@itziakos pointed out that #277 introduced a potential regression: before #277, the event loop was always run in the `GUITestAssistant.tearDown` method. This PR restores the running of the event loop.

Always run the event loop during tearDown.

---

.travis.yml
pyface/tasks/tests/test_dock_pane_toggle_group.py
pyface/tests/test_about_dialog.py
pyface/tests/test_application_window.py
pyface/tests/test_confirmation_dialog.py
pyface/tests/test_dialog.py
pyface/tests/test_directory_dialog.py
pyface/tests/test_file_dialog.py
pyface/tests/test_heading_text.py
pyface/tests/test_message_dialog.py
pyface/tests/test_progress_dialog.py
pyface/tests/test_python_editor.py
pyface/tests/test_python_shell.py
pyface/tests/test_single_choice_dialog.py
pyface/tests/test_splash_screen.py
pyface/tests/test_split_application_window.py
pyface/tests/test_split_dialog.py
pyface/tests/test_split_panel.py
pyface/tests/test_widget.py
pyface/tests/test_window.py
pyface/ui/qt4/tests/test_progress_dialog.py
pyface/ui/qt4/util/modal_dialog_tester.py
pyface/ui/qt4/util/tests/test_modal_dialog_tester.py

This is an attempt to fix the issues with excess objects after tests have finished as identified by #254.  There is some hope that these may address the segfault issues we are seeing under PyQt.

Be more careful about object cleanup when tests finish

---

.travis.yml
pyface/tasks/tests/test_dock_pane_toggle_group.py
pyface/tests/test_about_dialog.py
pyface/tests/test_application_window.py
pyface/tests/test_confirmation_dialog.py
pyface/tests/test_dialog.py
pyface/tests/test_directory_dialog.py
pyface/tests/test_file_dialog.py
pyface/tests/test_heading_text.py
pyface/tests/test_message_dialog.py
pyface/tests/test_progress_dialog.py
pyface/tests/test_python_editor.py
pyface/tests/test_python_shell.py
pyface/tests/test_single_choice_dialog.py
pyface/tests/test_splash_screen.py
pyface/tests/test_split_application_window.py
pyface/tests/test_split_dialog.py
pyface/tests/test_split_panel.py
pyface/tests/test_widget.py
pyface/tests/test_window.py
pyface/ui/qt4/tests/test_progress_dialog.py
pyface/ui/qt4/util/modal_dialog_tester.py
pyface/ui/qt4/util/tests/test_modal_dialog_tester.py

This depends on #281, but PyQt5 tests seem stable so this PR removes them from the allow failures list.

Remove "allow failures" for PyQt5

---

pyface/action/action_manager.py
pyface/action/tests/test_action_manager.py

Fix #289 
When item that is not a `Group` is being added to `ActionManager` using `append`, the index is computed from the number of groups (by default there is one Group) rather than the number of items in the default group.  So items were being inserted before index 1, hence the order was wrong.
This PR fixes this.
(Note: `Group` does not provide `__len__`, it would be nice if it did.)

Fix: Ordering of items being appended to the default group of ActionManager

---

pyface/i_widget.py
pyface/i_window.py
pyface/tests/test_widget.py
pyface/tests/test_window.py
pyface/ui/qt4/util/tests/test_modal_dialog_tester.py
pyface/ui/qt4/widget.py
pyface/ui/qt4/window.py
pyface/ui/wx/widget.py
pyface/ui/wx/window.py
pyface/workbench/__init__.py

Apart from general utility, this will permit better integration with TraitsUI `visible_when` and `enabled_when` (the long-term aim here is to eventually generalise the TraitsUI `View` buttons with Pyface objects).

Add visible and enabled traits to base Widget interface

---

pyface/base_toolkit.py
pyface/tests/test_new_toolkit/init.py
pyface/ui/null/init.py
pyface/ui/qt4/init.py
pyface/ui/wx/init.py
setup.py

This is the first step in allowing setting `ETS_TOOLKIT=qt` instead of `qt4`.  Currently wont work because TraitsUI will break
Also generalize `Toolkit` for use in other packages (eg. TraitsUI, Enable, etc.), as this will be useful in rolling out support for `pkg_resource`-based toolkit discovery.

Add 'qt' as a synonym for 'qt4' for ETS_TOOLKIT

---

docs/source/conf.py
setup.py

This consists of:
- use HTTP instead of HTTPS for docs in setup.py because of limitations of github pages.
- use default favicon from enthought-sphinx-theme

Small documentation fixes

---

pyface/qt/__init__.py

I am writing a package where I would like the Qt GUI to be optional.  I expect that saying `import pyface.qt` without a Qt API will fail -- but it seems that the `else` clause is attached to the `try / except` construct, not the `for` loop.
This PR removes 8 spaces and restores the expected behavior.

qt: Actually raise if we can't find at QT api

---

pyface/qt/QtGui.py

This PR resolves a crash in Mayavi when using pyface 6.0 and PyQt 5.6. 
The crash can be reproduced by trying to drag the Tab labeled "Mayavi Scene 1" in the screen shot below:
Trying to drag the tab crashes the application with the following traceback.
```
File "/Users/lee8rx/anaconda/lib/python3.5/site-packages/pyface/ui/qt4/workbench/split_tab_widget.py", line 897, in mouseDoubleClickEvent
self._resize_title_edit_to_current_tab()
File "/Users/lee8rx/anaconda/lib/python3.5/site-packages/pyface/ui/qt4/workbench/split_tab_widget.py", line 985, in _resize_title_edit_to_current_tab
tab = QtGui.QStyleOptionTabV3()
AttributeError: module 'pyface.qt.QtGui' has no attribute 'QStyleOptionTabV3'
```
The names QStyleOptionTabV3, QStyleOptionTabV2 and …

fix: add deprecated QStyleOption names in the Qt5 interfaces

---

pyface/application.py
pyface/tests/test_application.py

This is an attempt to get the application classes landed in the codebase by working incrementally, given that #198 and #285 are stalled.
This is a base application class taken from #198 and simplified slightly.

Base Application Class

---

pyface/tests/test_about_dialog.py
pyface/tests/test_application_window.py
pyface/tests/test_confirmation_dialog.py
pyface/tests/test_dialog.py
pyface/tests/test_directory_dialog.py
pyface/tests/test_file_dialog.py
pyface/tests/test_heading_text.py
pyface/tests/test_message_dialog.py
pyface/tests/test_progress_dialog.py
pyface/tests/test_python_editor.py
pyface/tests/test_python_shell.py
pyface/tests/test_single_choice_dialog.py
pyface/tests/test_splash_screen.py
pyface/tests/test_split_application_window.py
pyface/tests/test_split_dialog.py
pyface/tests/test_split_panel.py
pyface/tests/test_widget.py
pyface/tests/test_window.py

Should have been being used as a context manager, rather than as straight call.  Hopefully this may lead to better testing results in some environments.

Fix usage of event_loop() in tests

---

pyface/qt/__init__.py

Maybe related issues: enthought/mayavi#448, enthought/mayavi#460, enthought/mayavi#483
PyFace might select PyQt5 as the default API if it is installed even if Qt5 itself is missing.
This PR fix such an issue by ensuring that at least `QtCore` can be imported from the being-selected API, otherwise try the next one.

Make sure selected QtAPI actually provides QT support

---

pyface/qt/__init__.py

Python 3.5 (and maybe 3.6) requires that the Qt API package `module` be explicitly imported.
Fixes #346.

Better handling of Qt API imports

---

examples/python_editor.py
pyface/action/action.py
pyface/action/tests/test_action.py
pyface/action/tests/test_action_item.py
pyface/ui/qt4/action/action_item.py
pyface/ui/wx/action/action_item.py

Proper Pyface-level support for `Action`s which contain widgets.  Support is very basic, but works.

Add support for widgets in toolbars

---

pyface/i_clipboard.py
pyface/i_image_resource.py
pyface/workbench/__init__.py

Fixes warnings of this type:
```
/home/larsoner/python/pyface/build/lib/pyface/i_clipboard.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
And also fixes the `stacklevel` in an internal `PendingDeprecationWarning`.

FIX: Fix deprecation warnings

---

pyface/ui/qt4/tasks/split_editor_area_pane.py

In the `SplitEditorAreaPane`, a right click will bring up a context menu asking if you want to split the pane. When a tab is displaying a Chaco plot, a right click on the Chaco plot will interrupt still bring up that context menu. It is the case that Enable/Chaco is not `accept()`ing the Qt `QMouseEvent`s when it handles them as it should, but even when I fix that, I still get these context menus. I am not sure what's going with that.
In this PR, I only allow the context menu when it's the default empty page being displayed (e.g. in a fresh pane split) or when the mouse is in the tab bar, which is where I would expect to have pane-related actions to be available.
I invite feedback if this change in the user experience is acceptable to your applications.

BUG: Only display context menu when mouse is not on page.

---

pyface/ui/qt4/gui.py
pyface/ui/qt4/init.py
pyface/ui/wx/init.py

This checks to see if there is a ui dispatcher available for Traits when initializing the Pyface toolkit, and if not sets one.
This PR also includes a change that makes `_FutureCall` behave more like the TraitsUI `_CallAfter` for the `qt` toolkit when there is no delay for the callback.  This will potentially allow `_CallAfter` to be removed from TraitsUI in the future.
Fixes #362

Allow traits UI-based dispatch even when TraitsUI not available

---

pyface/fields/i_text_field.py
pyface/fields/tests/test_text_field.py
pyface/ui/qt4/fields/text_field.py
pyface/ui/wx/fields/text_field.py

Forgot tests for a couple of attributes.

Add some missing tests on text field

---

pyface/ui/qt4/util/gui_test_assistant.py

Checks to see if traitsui is available before patching StickyDialog.
Fixes #341 and fixes #353.

Fix TraitsUI dependency of GuiTestAssistant

---

pyface/tree/node_tree.py
pyface/ui/qt4/action/action_item.py
pyface/ui/wx/action/action_item.py
pyface/wx/drag_and_drop.py

Same idea as https://github.com/enthought/traitsui/pull/530

Fix deprecated getargspec calls in Python 3.

---

pyface/ui/qt4/action/action_item.py
pyface/ui/wx/action/action_item.py

Python 3 has different signature, and didn't take this into account in #369

Fix getargspec usage

---

etstool.py
pyface/qt/__init__.py

Ensure we set Qt API versions for PyQt4 before importing QtCore

---

setup.py

When installing a non-released PyFace from source rather than a Git clone, we end up with an invalid version number ending with `.dev0.dev0`. This PR fixes that.
```
mirzakhani:Desktop mdickinson$ edm env create test --force
Removing environment: test
Fetching indices for runtime repositories. done
Installing runtime... done
Fetching indices for package repositories....... done
Installing/removing package(s)
setuptools        [..........................................................................................................................................................................]
mirzakhani:Desktop mdickinson$ git clone git@github.com:enthought/pyface.git
Cloning into 'pyface'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: …
```

Fix bad dev version number when installing from non-Git clone.

---

docs/source/overview.rst

Nitpick: don't promote the antipattern of comparing integers using `is` rather than `==`. In this case it's harmless, but there's potential for the pattern to be copied elsewhere. Simpler to go for a blanket rule that integers should always be compared with `==`.

Don't compare integers using 'is'

---

pyface/dock/api.py
pyface/dock/dock_sizer.py
pyface/dock/dock_window.py
pyface/dock/dock_window_feature.py
pyface/dock/dock_window_shell.py
pyface/dock/feature_bar.py
pyface/dock/feature_tool.py
pyface/ui/wx/application_window.py
pyface/ui/wx/window.py

`6.1.0` seems to have a couple of broken imports, e.g.
```
In [1]: from pyface.action import api                                                                         
2019-05-28 08:58:43.581 python[83375:7529411] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-06b3548f7385> in <module>
----> 1 from pyface.action import api
~/Code/pyface/pyface/action/api.py in <module>
28 from .tool_bar_manager import ToolBarManager
29 from .traitsui_widget_action import TraitsUIWidgetAction
---> 30 from .window_action import CloseWindowAction, WindowAction
31 
32 # This part of the …
```

FIX wx backend local import

---

pyface/timer/do_later.py
pyface/timer/tests/test_do_later.py

* Fix API of DoLaterTimer to match earlier versions.
* Get tests working.
* Add tests for do_later and do_after.
* Add a little bit of slack to timing tests.
* Fix docstring
* We don't have a start time unless there is an expire.
* Better failure messages; add some slack into timing estimates.
* Make tests more robust (longer time, more slack)

Fix API of DoLaterTimer to match earlier versions (#389)

---

pyface/ui/qt4/action/action_item.py

The `ArgSpec` returned by `getargspec` does not contain an `argspecargs` attribute. This was introduced in the PR #370 .
See https://docs.python.org/3.6/library/inspect.html#inspect.getargspec for more information on the namedtuple returned by `getargspec`
fixes #392

Fix ArgSpec attribute access

---

pyface/qt/QtScript.py
pyface/qt/QtWebKit.py
pyface/ui/qt4/tests/test_qt_imports.py

This is the pyqt5 fix from #387 without the interference of changing the etstool infrastructure at the same time.

Fix imports for pyqt5 with webkit

---

CHANGES.txt
setup.py

Bugfix release.  Includes:
* Remove use of deprecated Traits get() method (#403)
* Fix pyqt5 webkit imports (#396)
* Remove use of cmp in fix_introspection_bug (#395)
* Update CI infrastructure (#394, #399)
* Update unittest imports (#391)
* Fix bug in argspec usage (#393)
* Fix regression in DoLaterTimer API (#389)

Release 6.1.1

---

pyface/ui/qt4/tasks/split_editor_area_pane.py

`TabDragObject.get_pixmap` switches on `QtGui.qt_api` to decide whether to use `widget.grab()` (available only in Qt 5) or `QPixmap.grabWidget(widget)` (available only in Qt 4).
But this seems like the wrong check, and will likely do the wrong thing for PySide 2. We're not interested in the pyqt version; we're interested in the Qt version.
This PR fixes that, and tidies up some nearby code in passing.

Fix a questionable version check.

---

examples/dock/dock_test3.py

This example file now runs for me under Python 3 / Qt. Beforehand, it failed with an `ImportError`.
cf: enthought/traitsui#577

Remove use of etsdevtools in an example file.

---

pyface/timer/tests/test_timer.py
pyface/timer/timer.py

This adds a test and fixes the issue.  It doesn't address setting the interval trait when the timer is running.

Fix timer issue #408.

---

pyface/ui/qt4/tasks/split_editor_area_pane.py

The `is` test for orientation can fail: there's no reason why the value returned from the `orientation()` call should be identical to one of the `QtCore.Qt.Horizontal` or `QtCore.Qt.Vertical` enumeration values.

Use equality rather than is when checking orientation.

---

pyface/dock/dock_window_feature.py
pyface/ui/qt4/gui.py
pyface/ui/wx/gui.py

I think it's safe to drop compatibility with Python 2.3 now.

Use decorator forms of classmethod and staticmethod.

---

docs/source/index.rst
pyface/tasks/action/schema.py
pyface/workbench/action/view_chooser.py
pyface/workbench/action/view_menu_manager.py

Be consistent about the package name: it's "Pyface", not "PyFace".
Mostly inconsequential, but the occurrence in the index page of the top-level docs is a bit glaring.

Fix some occurrences of PyFace (should be Pyface)

---

pyface/tasks/i_editor.py
pyface/tasks/i_task_pane.py
pyface/tasks/i_task_window_backend.py

Fixes some cases of #425: I concentrated on interfaces for non-outdated code pieces (so ignoring stuff in the `wizards` and `workspaces` packages).

Fix some comments that should be Traits doc-comments.

---

pyface/ui/qt4/util/gui_test_assistant.py
pyface/ui/qt4/util/tests/test_gui_test_assistant.py

When writing unit tests or regression tests for GUIs, I often want to assert that "if you run the event loop for long enough, such-and-such happens".
The `GuiTestAssistant.event_loop_until_condition` method does this, but it has a (to my eyes) strange API and feels awkward and error-prone to use:
- it has to be used as a context manager, even though it doesn't really fit the notion of a context manager because there's no setup step
- it's easy to accidentally misuse it (e.g., not as a context manager), and it's then not so easy to diagnose why things aren't working as expected
- it's making a unittest assertion (calling self.fail on timeout), but this isn't obvious from the name
This PR adds a new method `GuiTestAssistant.assertEventuallyTrueInGui` that can be used in the simple form:
``` …
```

Add GuiTestAssistant.assertEventuallyTrueInGui

---

examples/application/python_editor/python_editor_task.py

If you run the Python Editor example application (`pyface/examples/application/python_editor/`) and try to select a directory, you get a traceback on the console resembling the following:
```
File "/Users/mdickinson/.edm/envs/pyface-test-3.6-pyqt/lib/python3.6/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
self.dispatch(handler, *args)
File "/Users/mdickinson/.edm/envs/pyface-test-3.6-pyqt/lib/python3.6/site-packages/traits/trait_notifiers.py", line 553, in dispatch
handler(*args)
File "/Users/mdickinson/Enthought/ETS/pyface/examples/application/python_editor/python_editor_task.py", line 283, in handler
return self.create_editor(browser.selected_file)
File "/Users/mdickinson/Enthought/ETS/pyface/examples/application/python_e …
```

Fix: Don't try to open directories in PythonEditorTask

---

pyface/tasks/tests/test_action_manager_builder.py
pyface/tasks/tests/test_topological_sort.py
pyface/tests/test_clipboard.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py

Trivial PR that eliminates one cause of deprecation warnings seen during the test run.

Eliminate deprecation warnings about assertEquals

---

pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py

Two parts to this PR:
- clean up the context menu generation code, fixing some minor style problems
- add fix for the case where `get_context_menu` returns `None`, and make it explicit that `get_context_menu` can return `None`

Cleanups for SplitEditorAreaPane context menu management.

---

pyface/ui/qt4/tasks/split_editor_area_pane.py

Drive-by fix: fix an instance of true division that should be integer division (`QSplitter.setSizes` expects integers).
It's possible that the new sizes should be spelled `[(orig_size + 1)//2, orig_size//2]`, but the docs for `setSizes` indicate that Qt handles distributing extra space anyway, and the change in this PR matches current Python 2 behaviour (and probably current Python 3 behaviour, too).

Python 3 compatibility: replace true division with integer division.

---

pyface/ui/qt4/dialog.py

Out of the box, Windows dialogs have an extra "?" button in their title bar that does nothing (and looks ugly). This PR turns it off.
Before:
After:
Test script:
```python
from pyface.api import MessageDialog
dialog = MessageDialog(message="just testing long dialog message")
dialog.open()
```

Don't show the context help button in Windows dialogs.

---

pyface/ui/qt4/message_dialog.py
pyface/ui/qt4/tests/test_message_dialog.py

With a Qt backend, message dialogs that don't contain any details have a single "Ok" button, and can be closed by clicking on the close button or pressing the Esc key. This is fine.
Dialogs that _do_ have details have an extra "Show details..." button (at least on macOS), and can no longer be closed by clicking on the close button or pressing Esc. This is surprising behaviour.
This PR ensures that the close button and the Esc key work to close the dialog in both cases.
Fix has been manually tested on macOS; ~I'll test on Windows and Linux~ Tested manually on Windows and Linux, too.

Ensure close button and ESC key close message dialogs under Qt.

---

pyface/ui/wx/tasks/advanced_editor_area_pane.py
pyface/ui/wx/tasks/main_window_layout.py
pyface/ui/wx/tasks/split_editor_area_pane.py
pyface/ui/wx/tasks/task_window_backend.py

These imports failed for me when trying to import envisage.plugins.ipython_kernel.ipython_kernel_ui_plugin.IPythonKernelUIPlugin

Fix relative imports for wx tasks

---

pyface/qt/__init__.py

PyQt 4.12.2 changes to use a vendorized `sip`.  See https://www.riverbankcomputing.com/static/Docs/PyQt4/incompatibilities.html#pyqt-v4-12-2
This also makes an update to only call `prepare_pyqt4` on Python 2, as it isn't needed in Python 3.
See #450 for more discussion.

Support PyQt 4.12.2

---

pyface/util/fix_introspect_bug.py

- types.TupleType is gone in python3. isinstance(object, tuple) should work equally well on python 2.7. 
- isinstance check with object is also required to avoid infinite recursion on python 3
- parameter name object changed  to obj to avoid conflict with builtin object

Python3 compatibility updates in fix_introspect_bug

---

etstool.py

Fixes #439, by:
- locating the EDM executable
- replacing edm.bat with the edm.exe that it wraps, on Windows
- allowing the minimal magic involved in locating the EDM executable to be overridden by the user, either via an option or an environment variable.

Allow non-EDM environments to be used to run etstool.py on Windows

---

pyface/ui/qt4/util/gui_test_assistant.py

This changes the deprecated `traits` attribute name into `traits_name`, from the (privately imported) `TraitsChangeCollector`. This was renamed in https://github.com/enthought/traits/pull/343.
I realize that this code may be obsoleted by https://github.com/enthought/pyface/pull/447, but having one less `DeprecationWarning` for pyface end users would be a good thing, in the meantime.

MAINT: Update deprecated attribute name.

---

.travis.yml
appveyor.yml
install-edm-linux.sh
install-edm-osx.sh
install-edm-windows.cmd

This PR updates the CI systems to use the most recently released EDM (version 2.0.0).

Build: update Travis CI and Appveyor to use EDM 2.0.0.

---

pyface/dock/dock_window.py
pyface/ui/wx/image_button.py

Replace uses of the convenience trait types `false` and `true` with the corresponding `Bool` traits.

Replace uses of trait types 'false' and 'true' with 'Bool'

---

pyface/resource/resource_factory.py
pyface/ui/wx/python_shell.py
pyface/wx/drag_and_drop.py
pyface/wx/image_cache.py
pyface/wx/shell.py
pyface/wx/spreadsheet/font_renderer.py

This PR is possibly a little late. However ...
While removing support for old-style classes from Traits, I found some surprises, once of which was the `ResourceFactory` class from Pyface.
This PR turns that class and a handful of other old-style classes into new-style classes.

Turn some old-style classes into new-style classes

---

pyface/action/action_manager.py

Fix typo in action manager docstring

---

.travis.yml
appveyor.yml
ci-src-requirements.txt
etstool.py
setup.py

Test against the master branch of Traits rather than the latest release since there have been a lot of changes.
This means turning off Python 2.7 testing.  We also stop running CI against 3.5 because it is not giving much information that testing on 3.6 isn't already giving us.

Test against Traits master

---

pyface/tests/test_ui_traits.py
pyface/ui_traits.py

Tests weren't failing because the imports were already being guarded.  This now means we need Traits 6.0.

Replace use of default value constants with DefaultValue Enum

---

pyface/i_about_dialog.py
pyface/tests/test_about_dialog.py
pyface/ui/qt4/about_dialog.py
pyface/ui/wx/about_dialog.py

Closes #466 
As per offline discussion with @corranwebster , we decided to leave the existing Enthought and Riverbank copyright lines as they are, and add an optional trait that will allow users to include their own copyright notices. This new trait works exactly as the `additions` trait, but prepends each line with `Copyright (c) `.
I also had to refactor a bit both `ui/qt4/about_dialog.py` and `ui/wx/about_dialog.py` to accommodate a new `AboutDialog._create_html()` method, which builds the html shown in the dialog. This allows to properly test its content, something that was missing so far.

Include additional copyright notices in AboutDialog

---

pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/action/menu_manager.py
pyface/ui/wx/action/action_item.py

This PR approaches #483 
We add `_on_action_image_changed` to the Qt `_MenuItem`, `_Tool` and `_Menu`, and to the wx `_MenuItem`. We add `_on_action_tooltip_changed` to the Qt `_MenuItem` and `_Tool`.
- Implemented the `_on_action_image_changed` method that sets the control icon to the icon provided by the `action.image.create_icon()`.
- Implemented the `_on_action_tooltip_changed` method that sets the tooltip provided by the `action.tooltip`.

Action image (icon) attribute UI update

---

pyface/dock/dock_window_shell.py
pyface/ui/wx/image_button.py
pyface/ui/wx/python_editor.py

A few more fixes for wxPython 4.  The most important is the change to the `SetColour` call in the `ImageButton` class which was breaking the TraitsUI `ButtonEditor`.

More fixes for wxpython 4

---

pyface/dock/idockable.py

This is mainly needed to allow TraitsUI autodoc to work cleanly.

Avoid wx imports in pyface.dock interfaces

---

pyface/tests/test_application_window.py
pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/action/menu_manager.py
pyface/ui/qt4/action/tool_bar_manager.py
pyface/ui/qt4/application_window.py

Part of #258 
Before destroying control of `ApplicationWindow`, trait change handlers from downstream widgets are disconnected.
The structure of these underlying widgets and their managers is fairly complex so it's hard to say if it is necessary to disconnect these trait change handlers and if it helps with garbage collection. I attempt to evaluate the risks and the benefits but there might be things that I've missed.
____
**`_Menu` in `menu_manager.py` and `_ToolBar` in `tool_bar_manager.py`**
They connect their methods to Python `MenuManager` and `ToolBarManager` object traits, but as far as I know that shouldn't prevent any of the objects from being garbage collected. And when either side is deleted, the connection should break. However, if for some reason those connections remain …

Disconnect trait change handlers from downstream ApplicationWindow widgets

---

pyface/tests/test_progress_dialog.py
pyface/ui/qt4/about_dialog.py
pyface/ui/qt4/dialog.py
pyface/ui/qt4/progress_dialog.py

Part of #258 
Adds additional cleanup (disconnecting qt signals) to `destroy` methods of some qt dialogs.
Also adds one additional smoke test for `ProgressDialog`.

Audit qt dialogs connections

---

pyface/ui/qt4/util/image_helpers.py

This should stop the sporadic test failures caused by referencing memory which has been freed and used by something else.  The fix is to attach the numpy array with the allocated memory to the QImage, so that the lifetime of the array is at least as long as that of the QImage.
Fixes #517

Fix errors from incorrect QImage memory management.

---

pyface/ui/qt4/action/menu_manager.py
pyface/ui/qt4/action/tool_bar_manager.py

Additional fix following #541 
Use Traits `List()` so that each instance of manager has its own list for tracking `_menus` and `_toolbars`.

Use Traits List for _menus and _toolbars

---

pyface/ui/qt4/console/bracket_matcher.py
pyface/ui/qt4/console/console_widget.py
pyface/ui/qt4/python_shell.py

Part of #258
Adds `disconnect_event_listeners` methods to downstream widgets which are called from within `_remove_event_listeners` of `PythonShell`.
Right after `_remove_event_listeners` a `deleteLater` is called on control. In this case all signals are connected to methods in main `control` hierarchy, so as long as control is deleted, the signals should be disconnected as well according to qt documentation. The benefits of adding disconnect are very small (or completely non-existent).
It's quite straightforward and safe (I think) to disconnect most of the signals here. And since the work is already done, it wouldn't hurt to add this.

Disconnect qt PythonShell downstream widget signals

---

.travis.yml
etstool.py

At the moment, traits is the only package installed from source as pyface is always installed from source on CI. The changes are almost the same as that in traits PR enthought/traits#479.
Exactly the same as the changes in https://github.com/enthought/traitsui/pull/914 except for replacing the word `"pyface"` with `"traitsui"`

Add cron job to install/test against packages from source

---

pyface/tasks/tests/test_advanced_editor_area_pane.py
pyface/tasks/tests/test_split_editor_area_pane.py
pyface/ui/qt4/tasks/advanced_editor_area_pane.py
pyface/ui/qt4/tasks/dock_pane.py
pyface/ui/qt4/tasks/editor_area_pane.py
pyface/ui/qt4/tasks/split_editor_area_pane.py

Part of #258 
Distinct things this PR does:
1. `DockPane` - disconnects signals from its control. Low risk - low reward kind of change. Doesn't hurt to add this.
2. Deletes connections to shortcuts via `_connections_to_remove` in classes providing `IEditorAreaPane`. It is good to disconnect these shortcuts because if something goes wrong and the objects are not deleted, the handlers can still be activated via keyboard events. So the reward is fairly high. The risk with current code is low because it is only disconnecting what is added to the list and there are no other disconnects. The problems might arise if someone decides to disconnect the shortcuts elsewhere and doesn't remove them from the list. But maybe that should be considered a case of "Don't do that".
3. Removes reference to …

Disconnect qt signals in qt implementation of pyface.tasks

---

pyface/ui/qt4/tasks/main_window_layout.py
pyface/ui/qt4/tasks/tests/test_main_window_layout.py

This PR is an alternative to #535 that also closes #442 
@rahulporuri Could you please check if this approach works for your use case?

Fix dock pane layout

---

.travis.yml
CHANGES.txt
appveyor.yml
etstool.py
pyface/ui/qt4/tasks/main_window_layout.py
pyface/ui/qt4/tasks/tests/test_main_window_layout.py
pyface/ui/qt4/util/image_helpers.py

This PR backports bug fixes for the 7.0.1 release.
- Backported changes from #546 and #545.
- Updated Changelog
- Updated CI build configuration too so this PR can be tested on CI.
- Backported changes to `etstool.py install` for wx dependencies (which is a part of #512 that needed to stay)

Backport bug fixes for 7.0.1 release

---

pyface/ui/qt4/code_editor/pygments_highlighter.py
pyface/ui/qt4/code_editor/tests/test_code_widget.py

This PR fixes the issue seen in https://github.com/enthought/traitsui/issues/982
pygments tokens are hierarchical: styles can define the styling for groups of tokens rather than an individual token type. The `Style.style_for_token` function is a lower level function that does not resolve the closest token group for a given leaf token. One needs to resolve the token group supported by a given style before calling `style_for_token`. 
This is consistent with how pygments handles the same situation: 
https://github.com/pygments/pygments/blob/4cd83f9e5e16e4bafa208e5be5bb3a9dc1ed813a/pygments/formatters/svg.py#L176-L178

Fix CodeWidget crashing due to KeyError from pygments Style.style_for_token

---

CHANGES.txt
pyface/ui/qt4/code_editor/pygments_highlighter.py
pyface/ui/qt4/code_editor/tests/test_code_widget.py

This PR backports the fix from #566 for the 7.0.1 release.
Note that the changelog is updated here (which needs review).

Backport fix to CodeWidget for 7.0.1 release

---

pyface/ui/qt4/about_dialog.py

Fixed copyright upper bound

---

CHANGES.txt
pyface/ui/qt4/about_dialog.py

This PR just backports #573 to the maintenance 7.0 branch - in preparation for the 7.0.1 bug fix release.

Backport #573 to v 7.0 maintenance branch

---

setup.py

This PR does has two commits : 
- The first sets IS_RELEASED to True, making the 7.0.1 release of pyface
- The second flips IS_RELEASED back to False and updates the verison to 7.0.2 to continue development on the maintenance branch
ref : #557 for the release issue

Bug fix release for version 7.0.1

---

CHANGES.txt

Instead of manually cherry-picking commits from the maintenance branch to update the changelog on master, we just did it in one go. The changelog entry here matches with that on the maintenance branch `maint/7.0`

Update changelog on master for 7.0.1

---

docs/source/applications.rst
docs/source/overview.rst
docs/source/toolkits.rst

Addresses simple errors in #592.  
May be good to do another PR adjusting code examples to be more self-contained/show their outputs.

Fixing typos and syntax errors in Pyface Docs

---

pyface/tasks/tests/test_editor_area_pane.py
pyface/tasks/tests/test_topological_sort.py

fixes #526 
This change address the first two bullets on issue #582
The remaining bullets will be done in separate PRs.

replacing assert_ with assertTrue to avoid deprecation warning

---

examples/application/python_editor/python_editor.py
examples/application/python_editor/python_editor_application.py
examples/application/python_editor/python_editor_task.py
pyface/action/gui_application_action.py
pyface/action/window_action.py
pyface/splash_screen_log_handler.py
pyface/tasks/action/dock_pane_toggle_group.py
pyface/tasks/action/task_toggle_group.py
pyface/tasks/action/task_window_toggle_group.py
pyface/tasks/action/tasks_application_action.py
pyface/tests/test_clipboard.py
pyface/tests/test_confirmation_dialog.py
pyface/tests/test_dialog.py
pyface/tests/test_message_dialog.py
pyface/tests/test_single_choice_dialog.py
pyface/tests/test_splash_screen_log_handler.py
pyface/ui/qt4/code_editor/find_widget.py
pyface/ui/qt4/code_editor/gutters.py
pyface/ui/qt4/code_editor/pygments_highlighter.py
pyface/ui/qt4/code_editor/replace_widget.py
pyface/ui/qt4/mimedata.py
pyface/ui/qt4/tests/test_message_dialog.py
pyface/ui/qt4/util/modal_dialog_tester.py
pyface/ui/qt4/workbench/split_tab_widget.py
pyface/ui/wx/grid/grid.py

addresses a part of #601 
ref python docs - https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str
> Changed in version 3.3: For backwards compatibility with the Python 2 series, the `u` prefix is once again permitted on string literals. It has no effect on the meaning of string literals and cannot be combined with the `r` prefix.

Remove all of the u prefix on strings

---

pyface/color.py
pyface/tests/test_color.py
pyface/ui/null/color.py
pyface/ui/qt4/color.py
pyface/ui/wx/color.py

This is the color class from #534 pulled out into a separate PR.
This does not include any of the string parsing, trait type, or dialog classes.

Toolkit independent color class for Pyface

---

README.rst
etstool.py
setup.py

Added a running the test suite section on readme.
Pypi description will now be first part of readme.  Full readme is what will appear on GitHub, with later sections being more tailored towards contributors.
Also changed etstool.py docstring and readme to specify test suite can be run by 
```
python etstool.py test-all
```
not 
```
python etstool.py test_all
```
As when I try to run with an _ I get an error but with - runs as expected.
fixes #570

Add test suite info to readme, not Pypi

---

etstool.py

For developers making frequent changes to the code (e.g. switching between branches), it is more convenient to install the source in editable mode.
This PR adds the `--editable` flag to the `etstool`. This flag can also be found in `traits` and `traitsui` etstool.

Add --editable flag to etstool install command

---

etstool.py

fixes #626 
I tried to make passing quiet optional, but the default behavior.  I wasn't sure if you meant to make it the default behavior for the CI (making it optional but then when called in the travis/appveyor files they use quiet) or default within etstool which is what I tried.

Reduce verbosity when installing package in CI

---

examples/tasks/enaml/employee_view.enaml
examples/tasks/enaml/empty_form.enaml

This is what the final window looks like after the fix.
The example is found in https://github.com/enthought/pyface/tree/master/examples/tasks/enaml

fixed a syntax error encountered when running enaml example

---

pyface/gui_application.py
pyface/qt/__init__.py
pyface/timer/i_timer.py
pyface/ui/qt4/mimedata.py

remove conditionals on python version

---

pyface/dock/dock_sizer.py

fixes #558 
also fixes https://github.com/enthought/traitsui/issues/1074
In line 625 we set `self._save_clip = dc.GetClippingBox()` However, GetClippingBox returns a 5-tuple 
Returns
( bool, x, y, width, height )
Only the last 4 are needed as arguments to SetClippingRegion, so `GetClippingRect()` was used instead which returns the correct arguments.

Replace GetClippingBox() with GetClippingRect() to avoid wrong argument errors

---

pyface/ui/qt4/util/tests/test_image_helpers.py

This PR removes an invocation of `print` in a test. Probably left behind from debugging.

Maint: Remove a print call in test

---

.travis.yml
etstool.py
pyface/__init__.py
pyface/data_view/data_models/tests/test_array_data_model.py
pyface/data_view/tests/test_abstract_value_type.py
pyface/data_view/tests/test_data_view_widget.py
pyface/data_view/value_types/tests/test_constant_value.py
pyface/data_view/value_types/tests/test_editable_value.py
pyface/data_view/value_types/tests/test_no_value.py
pyface/data_view/value_types/tests/test_numeric_value.py
pyface/data_view/value_types/tests/test_text_value.py
pyface/util/testing.py

Closes #632
This PR adds a CI job to test against Traits 6.0.
Tests for the data views are skipped and associated imports requiring `traits.api.observe` are wrapped in a condition (in tests only).
Data view is a new feature not yet released so it is okay for it to depend on Traits 6.1 as downstream projects can opt-in.

Add CI job targeting Traits 6.0

---

pyface/__init__.py

Currently `pip install pyface[pyqt5]` fails with not being able to find a distribution named `pyqt` with version `>=5`. This PR fixes that.

Fix extras_require for PyQt5

---

pyface/__init__.py
pyface/data_view/data_models/tests/test_array_data_model.py
pyface/data_view/tests/test_abstract_value_type.py
pyface/data_view/tests/test_data_view_widget.py
pyface/data_view/value_types/tests/test_constant_value.py
pyface/data_view/value_types/tests/test_editable_value.py
pyface/data_view/value_types/tests/test_no_value.py
pyface/data_view/value_types/tests/test_numeric_value.py
pyface/data_view/value_types/tests/test_text_value.py
pyface/util/testing.py

Closes #662
Instead of wrapping import and individual test case with condition on traits version, this PR moves the skip over to `pyface.load_tests` to skip all tests with `.data_view.` in the test name.  The idea is that it would skip tests in `pyface.data_view.*`, `pyface.qt.data_view.*` etc. when we run `python -munittest discover pyface`
Side-effect:
- `pyface.data_view.index_manager` does not depend on Traits 6.1. Previously `pyface.data_view.tests.test_index_manager` is not skipped in the Traits ~6.0~ 6.1 test run. Now it is.
- The skip message has changed from `'Test requires Traits >= 6.1'` to `"Test excluded via pattern '\\.data_view\\.'"`
Note:
- The logic `load_tests` is only used when running the test suite using `unittest discover pyface`. The tests won't be skipped if the …

Skip tests requiring traits 6.0 using load_tests instead

---

examples/explorer.py
examples/multi_toolbar_window.py
pyface/ui/wx/viewer/table_viewer.py

fixes #647 
Also, there was a deprecation warning when running explorer.py on wx that I tried to fix here.  It probably could have been in its own PR, but it was so small I just added it here.  
Also as a side note I don't really understand what exactly the multi_toolbar_window.py is really supposed to demonstrate.  It also seems like the window isn't displaying correctly.  
Notice the "Foo" and "Bus" seem to overlap.  I will open a separate issue for this.

Mention in docstrings that examples aren't implemented on qt backend 

---

etstool.py

There was a trailing whitespace that my IDE keeps trying to fix it for me whenever I save the file.
This PR lints the entire file for flake8 compliance.
I added `noqa` to silence flake8 in cases where it is better/readable to keep the integrity of a command than trying to break it up.

Flake8 etstool.py

---

examples/data_view/array_example.py
examples/data_view/column_example.py
examples/menu_manager.py
examples/tool_palette.py

fixes #639 
The docstrings are all still very trivial and could be added to, but these are consistent with the other examples.

adding trivial docstrings

---

pyface/ui/wx/clipboard.py

Fixes #674
Under X11-based systems, Wx can pull values to be pasted either from the clipboard, or from the current ("primary") selection. This change ensures that the Pyface clipboard is always getting data from the clipboard, and never from the current selection.
This is implemented via a context manager which ensures that the wider application state controlling the source of paste data is unmodified, minimizing the likelihood of problems in the wider application (particularly if Pyface is being used as a library). The context manager will do nothing if called from a non-X11 system.

Fix Wx/linux clipboard test failures

---

.travis.yml
etstool.py
pyface/ui/wx/clipboard.py

This updates the Wx CI to use the wxPython package for Ubuntu 16.04, which is now the default version of Ubuntu used in Travis CI (updated from 14.04 when wxPython testing was last updated).
It also turns on Python's faulthandler when running tests via etstool, so segfaults and other hard crashes should give better feedback.
This needs #676 to be merged first.

Update Wx CI

---

pyface/ui/wx/clipboard.py

Adds a closing context manager, plus adds logging for load failures and a few additional clean-ups.  Purely opportunistic since we have been in the code for this.

Drive-by clean-up of wx clipboard code

---

pyface/ui/wx/viewer/table_viewer.py

See comments on #667.
We do not currently see the deprecation warning when using a wx environment created by the etstool in pyface as the development environment has pinned an older version of wxPython.
However, when using an environment with newer wx, there was the following deprecation warning (found when running the explorer.py example):
```
/Users/aayres/Desktop/pyface/pyface/ui/wx/viewer/table_viewer.py:313: wxPyDeprecationWarning: Using deprecated class. Use ItemAttr instead
self._even_row_attribute = wx.ListItemAttr()
/Users/aayres/Desktop/pyface/pyface/ui/wx/viewer/table_viewer.py:318: wxPyDeprecationWarning: Using deprecated class. Use ItemAttr instead
self._odd_row_attribute = wx.ListItemAttr()
```

replacing ListItemAttr with ItemAttr to avoid deprecation warning

---

pyface/data_view/abstract_value_type.py
pyface/data_view/value_types/constant_value.py
pyface/data_view/value_types/no_value.py
pyface/data_view/value_types/tests/test_constant_value.py
pyface/data_view/value_types/tests/test_no_value.py
pyface/ui/qt4/data_view/data_view_item_model.py
pyface/ui/wx/data_view/data_view_model.py

Straight-forward addition of a tooltip channel for data view `ValueTypes`.  There is some incompleteness around what the default tooltip should be for numeric and text values, so for now it is something to be handled by subclassing.  Appropriate usage may become clear after sufficient use.
Only works on Qt backend.

Tooltips for DataViews

---

docs/source/conf.py
pyface/tasks/i_editor_area_pane.py
pyface/tasks/task_window.py
pyface/tree/node_manager.py
pyface/ui/wx/tree/tree.py
pyface/ui/wx/workbench/editor_set_structure_handler.py
pyface/ui/wx/workbench/view_set_structure_handler.py
pyface/workbench/i_view.py
pyface/workbench/workbench_window.py

Ref : https://docs.python.org/3.6/library/logging.html#logging.Logger.warning

logger.warn is deprecated, use logger.warning instead

---

etstool.py

This PR adds a new `shell` click command - which when run activates the development environment for traits. The usual command line options are available to choose the environment name and the runtime/toolkit version of the development environment. Underneath the hood, the click command just uses the `edm shell` command with the appropriate environment name, which is why the docstring for the click command is _almost_ the same as that of `edm shell`.

Add a new shell click command

---

pyface/ui/qt4/heading_text.py

Remove border from Qt HeadingText.

---

examples/data_view/column_example.py
pyface/data_view/abstract_value_type.py
pyface/data_view/tests/test_abstract_value_type.py
pyface/data_view/value_types/api.py
pyface/data_view/value_types/bool_value.py
pyface/data_view/value_types/tests/test_bool_value.py
pyface/ui/qt4/data_view/data_view_item_model.py

This PR adds support for checkboxes in the data view; and adds a bool value type that uses them.
The bool value type uses a different code path than the editable values because the checkboxes are always interactable and don't require a click to activate an editor.

DataView checkboxes

---

etstool.py
pyface/color.py
pyface/tests/test_clipboard.py
pyface/tests/test_color.py
pyface/util/color_parser.py
pyface/util/tests/test_color_parser.py

This is the parser component of #534 pulled out into a separate PR.
The aim here is to accept a superset of CSS colours that can be provided to specify a colour in a more programmer friendly way.  The parser may also potentially be used in text-style editors for Color instances.
Also fixes #620.

Parser for Pyface Color classes

---

pyface/data_view/data_wrapper.py
pyface/data_view/i_data_wrapper.py
pyface/data_view/tests/test_data_wrapper.py
pyface/ui/qt4/data_view/data_wrapper.py
pyface/ui/qt4/data_view/tests/test_data_wrapper.py
pyface/ui/wx/data_view/data_wrapper.py
pyface/ui/wx/data_view/tests/test_data_wrapper.py

To support drag and drop for data views, we need an abstraction that wraps Qt `QMimeData` and Wx `DataObject` classes, both of which store serialized bytes tagged by mimetype.
This PR provides a generic wrapper for both, along with a simple `DataFormat` class for handling different mimetypes.  Planned design for drag and drop support is that when a drag is started, the data view will create a wrapper object and supply data in appropriate formats; and when an object is dropped the data view will supply a list of data formats that are supported and they will be tried in order.  The deserialized data will then be supplied to `set_data` or similar methods on the class.
Cut, Copy and Paste will work similarly, when supported, but that is low priority.
Note that both Wx and Qt provide special …

Add DataWrapper classes to support abstracted DnD and clipboard

---

examples/data_view/column_example.py
examples/data_view/row_table_example.py
pyface/data_view/value_types/color_value.py
pyface/data_view/value_types/constant_value.py
pyface/data_view/value_types/tests/test_color_value.py
pyface/data_view/value_types/tests/test_constant_value.py

This PR does two things:
- switches from `Instance(Color)` to `PyfaceColor` traits
- fixes #708 (`ColorValue` was using an older iteration of the `ValueType` API)
We will probably revisit `ColorValue` again once there are custom editors available.

DataView Color clean-up

---

examples/data_view/array_example.py
pyface/data_view/i_data_view_widget.py
pyface/ui/qt4/data_view/data_view_widget.py

This is basic drop support using the existing `IDropHandler` interface.  This is designed mainly for supporting entire-table drop actions (eg. dropping a file with alternative data onto a table, or dropping an object that will be inserted into a location automatically).
With some toolkit-specific code could be used for deeper introspection of the drop target and handle dropping to replace, insert, or even move values.  However, at some point we would like to expose an additional API that makes these sorts of operations easier.
This PR includes adding support for dropping `.npy` format files onto the array example to replace the array being viewed with one loaded from the `.npy` file.

DataView drop handler

---

docs/source/index.rst
docs/source/traits.rst

Add documentation for the `Color` class and `PyfaceColor` trait.

Color and PyfaceColor Documentation

---

pyface/ui/qt4/code_editor/code_widget.py
pyface/ui/qt4/code_editor/find_widget.py
pyface/ui/qt4/code_editor/gutters.py
pyface/ui/qt4/code_editor/replace_widget.py

fixes #653 
This PR simply uses QFontMetrics().horizontalAdvance() instead of QFontMetrics().width()when possible (horizontalAdvance was introduced in Qt 5.11) to avoid a deprecation warning.
Same fix was done in an open PR on traitsui: https://github.com/enthought/traitsui/pull/1315

Fix QFontMetrics.width deprecation warning

---

pyface/ui/qt4/system_metrics.py

fixes #724 
For discussion of the motivation see https://github.com/enthought/traitsui/pull/1322
This PR simply replaces calls to `screeGeometry` and `geometry` with calls to `availableGeometry` as we are really interested in the available screen space not the full screen space.

Use availableGeometry when computing screen size to only get available space on scree

---

appveyor.yml

[Targeting `maint/7.1`]
This makes sure PRs against maint/7.1 are also tested on Appveyor.

Add maint/7.1 to the branches being tested on Appveyor

---

appveyor.yml

This PR updates the Appveyor configuration to accept builds from maintenance branches. Without this setting, PRs targeting a maintenance branch won't be built on Appveyor.
This is such that in the future when new maintenance branches are created from master, there is no need to change this setting again.
See https://www.appveyor.com/docs/branches/#white--and-blacklisting

Update Appveyor config to accept builds targeting maintenance branches

---

ci-src-requirements.txt

[Targeting maint/7.1]
Little did I know pyface also installs traitsui's master. So we need to set the source dependency to point to TraitsUI maintenance branch for Pyface maintenance branch.
(Added this step in #714 for future reference.)

Use TraitsUI maintenance branch for Pyface 7.1 maintenance branch

---

docs/source/data_view.rst
pyface/data_view/i_data_view_widget.py

Closes #741
This PR adds a mention that the data view API is provisional for the 7.x series.
A similar mention will be included in the release of 7.1.0, but since this applies to the 7.x series, it is more efficient and discoverable to simply mentions this in the user manual.
See #756 for removing these mentions when the API is no longer provisional.

Mention the data view API being provisional in the User Manual

---

pyface/data_view/i_data_view_widget.py

Fix #743
The warning is triggered when this observer is used:
https://github.com/enthought/pyface/blob/86c9a9c629d7a77ac06fae563f54e0aba231c554/pyface/ui/qt4/data_view/data_view_widget.py#L245
which is defined in a different place to where the trait is defined. I had to dive into some private states on the class to find it.

Set comparison mode to identity for MDataViewWidget.exporters

---

.gitattributes

https://github.com/enthought/pyface/pull/747 should have included this change such that the archive commit hash is replaced properly.
This PR fixes the omission.

Add the missing gitattributes for git archive commit hash

---

pyface/data_view/data_models/api.py
pyface/data_view/data_models/tests/test_api.py
pyface/data_view/exporters/tests/test_api.py
pyface/data_view/tests/test_api.py

Targeting #750
This PR
- Adds tests for the api modules.
- Allows NumPy to be absent and still be able to import data models that don't require NumPy
The treatment mirrors the import of ArrayEditor in TraitsUI:
https://github.com/enthought/traitsui/blob/7b53731606959dfaa7b2e3e8089d00e7a771e312/traitsui/api.py#L29-L33
Ideally we should have a CI job that has the most minimal requirements, and in the case of Qt, NumPy is not an install requirement. I just ran the tests locally with NumPy removed from my environment.

Test API modules in pyface.data_view

---

docs/source/examples/data_model_indices.py
docs/source/examples/dict_data_model.py
examples/data_view/array_example.py
examples/data_view/column_data_model.py
examples/data_view/column_example.py
examples/data_view/row_table_example.py
pyface/data_view/api.py
pyface/data_view/data_models/api.py
pyface/data_view/data_models/tests/test_api.py
pyface/data_view/exporters/api.py
pyface/data_view/exporters/tests/test_api.py
pyface/data_view/tests/test_api.py
pyface/ui/qt4/system_metrics.py

This PR adds `api.py` modules to the various `data_view` sub-packages.  It also modifies examples and documentation to use the these modules when importing objects.
This fixes #740.

Add api.py to data view packages

---

etstool.py

This PR renames the `api-docs` click command to `docs`. Now, traitsui and pyface have the same command name - reducing
unnecessary cognitive overhead.
traitsui - 
```
> edm run -e bootstrap -- python -m etstool
Usage: etstool.py [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
cleanup     Remove a development environment.
docs        Autogenerate documentation
flake8      Run a flake8 check in a given environment.
install     Install project and dependencies into a clean EDM environment.
shell       Create a shell into the EDM development environment (aka...
test        Run the test suite in a given environment with the specified...
test-all    Run test_clean across all supported environment combinations.
test-clean  Run tests in a clean environment, …
```

Rename api-docs click command to docs

---

pyface/ui/qt4/util/gui_test_assistant.py

fixes #445 
This PR updates the docstring for `GUITestAssitant.assertTraitChangesInEventLoop` - stating that the `condition` takes `obj` as the argument.

Fix a docstring in a GUITestAssistant method.

---

pyface/ui/qt4/util/tests/test_modal_dialog_tester.py

The tests were previously being skipped because they failed mysteriously on pyqt5 - on further investigation, I saw weird errors related to two of the tests - a missing AttributeError for `self.gui`. We shouldn't be seeing the errors because `self.gui` exists on the super class `GUITestAssistant`. I did not investigate further why `self.gui` was missing.
I fixed the issue by simply using `GUI` from `pyface.api`
fixes #302

Get ModalDialogTester tests working on pyqt5

---

setup.py

This Pr contains 2 commits (Dont squash merge!) to set the `PRERELEASE` to rc2 and flip `IS_RELEASED`.

Release candidate 7.1.0rc2

---

pyface/ui/qt4/data_view/data_wrapper.py
pyface/ui/qt4/data_view/tests/test_data_view_item_model.py
pyface/ui/qt4/data_view/tests/test_data_wrapper.py

This makes sure that data is explicitly extracted from QByteArrays rather than relying on toolkit wrappers to autoconvert to bytes-like things.

Fix PySide2 bytearrays

---

setup.py

The first commit will be tagged as the release, and the second commit bumps the release version for development of 7.1.1

Pyface Release 7.1.0

---

CHANGES.txt
docs/source/data_view.rst
docs/source/traits.rst

The changelog has been being updated on `maint/7.1`. This PR brings the changelog back to master.

Bring changelog for Release 7.1.0 back to master

---

pyface/__init__.py

This PR resolves the following deprecation warning.
```
/Users/kchoi/.edm/envs/my_env/lib/python3.6/site-packages/pyface/__init__.py:77: DeprecationWarning: invalid escape sequence \.
exclusion_patterns.append("\.data_view\.")
```
Such warnings are even harder to spot than import time deprecation warning: They only occur the first time the Python file is byte-compiled, usually when the distribution is freshly installed.
The particular line being changed will be removed for #781. But this PR alone is justified and can be backported for bug fix releases.

Fix deprecation warning at compile time

---

ci-src-requirements.txt
etstool.py

fixes #775 
This PR updates CI/etstool module to install traitsui using edm instead of installing it from git source.

Dont install traitsui from git source

---

docs/source/timer.rst

fixes #793 
This PR fixes code formatting in timers docs. The issue was the use of `:` and `::` before the code block declaration.

Fix code formatting in timers docs

---

README.rst

This PR updates the README for Pyface (also visible on PyPI page) to provide installation instructions for optional dependencies.

Add installation instruction on README

---

pyface/timer/tests/test_timer.py

Closes #556
The explanation for the issue (though I cannot reproduce to confirm) is that the timer being tested may interact with the condition timer from the `GuiTestAssistant.event_loop_helper.event_loop_until_condition` such that the callback can be called more than 4 times. 
This PR updated the test so that it no longer requires the handler to have been called exactly 4 times.
More motivation:
The number of callbacks was not the core of the test objective: The behaviour we need to be testing is that the callback is called at or after (almost always after, allowing for some precision errors) the expected times when the timer is supposed to time out. Note also that timer is not accurate because the timer event cannot fire if the system is busy doing something else.

Fix sporadic Timer test failure on OSX + Qt

---

docs/source/toolkits.rst
etstool.py
pyface/__init__.py
pyface/base_toolkit.py
pyface/tests/test_toolkit.py

Use `importlib_metadata` (`importlib.metadata` starting python 3.8) instead of `pkg_resources`, specifically when searching through the entry points, not when looking for resources.
fixes #789

Use importlib_metadata instead of pkg_resources for toolkit entry points

---

pyface/i_about_dialog.py
pyface/i_application_window.py
pyface/i_confirmation_dialog.py
pyface/i_dialog.py
pyface/i_directory_dialog.py
pyface/i_file_dialog.py
pyface/i_gui.py
pyface/i_heading_text.py
pyface/i_image_cache.py
pyface/i_image_resource.py
pyface/i_message_dialog.py
pyface/i_progress_dialog.py
pyface/i_python_editor.py
pyface/i_python_shell.py
pyface/i_single_choice_dialog.py
pyface/i_splash_screen.py
pyface/i_split_widget.py
pyface/i_system_metrics.py
pyface/i_widget.py
pyface/i_window.py
pyface/wizard/i_wizard.py
pyface/wizard/i_wizard_page.py

This is a simple search and replace of `class MFoo(object):` with `class MFoo(HasTraits):`, combined with fixing of the imports where necessary.
Fixes #730.
This not intended to be part of the 7.1.0 release.

Have mixins inherit from HasTraits

---

.travis.yml
etstool.py

Doing so prevents the possibility of pip installing new versions of packages installed by edm.

Run pip install with no deps

---

etstool.py
pyface/__init__.py
pyface/resource/resource_manager.py
pyface/tests/test_image_resource.py

This is a sister PR to #790 
This PR replaces the use of `pkg_resources` to access files from packages with the use of `importlib_resources`.
Note : I dont expect this to work on master because the `importlib_resources` version available on edm is older than the latest
version available via PyPI (3.3.0).

Use importlib_resources instead of pkg_resources for resource files

---

pyface/ui/wx/tree/tree.py

I noticed this while trying to run the following example:
https://github.com/enthought/apptools/blob/master/examples/naming/explorer.py
And doing so I saw the following traceback:
```
$ python explorer.py 
01:52:11 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:52:11 PM: Debug: Adding duplicate animation handler for '1' type
01:52:11 PM: Debug: Adding duplicate animation handler for '2' type
01:52:11 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:52:11 PM: Debug: Adding duplicate animation handler for '1' type
01:52:11 PM: Debug: Adding duplicate animation handler for '2' type
01:52:11 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:52:11 PM: Debug: Adding duplicate animation handler for '1' type
01:52:11 PM: Debug: …
```

Add wx_id parameter to __init__ for Tree to avoid errors

---

pyface/i_widget.py
pyface/tests/test_widget.py

This adds `create` as a synonym for `_create` and uses it for `Widget` class tests.
This is the first part of #729.

Add a create method for IWidget

---

MANIFEST.in

This PR changes the manifest file to only include the image license and other relevant top level files, not all `txt` extension files.
On master, the following additional files are included in the sdist, which aren't included in this PR.
- `appveyor-clean-cache.txt`
- `CHANGES.txt`
- `ci-src-requirements.txt`
- `dev_requirements.txt`
- `doc-src-requirements.txt`

Dont include ALL txt files from root directory

---

dev_requirements.txt

This PR removes an unused requirements file.

Delete unused requirements file

---

pyface/api.py
pyface/util/_optional_dependencies.py
pyface/util/tests/test__optional_dependencies.py

Follow up from https://github.com/enthought/pyface/pull/796
In particular, this: https://github.com/enthought/pyface/pull/796#issuecomment-725538154
If PythonEditor and PythonShell cannot be imported because pygments is not available, it might help if we log a debug message so that downstream projects have more information when the import fails.
The alternative would be to emit a warning, but for developers who don't care about these two classes, this could be too noisy.

Log debug message if import PythonShell and PythonEditor fail in api.py

---

.travis.yml

macOS minutes are expensive; remove macOS builds from the Travis CI configuration. Longer term, we'll plan to migrate to GitHub Actions.

Remove macOS builds from Travis CI configuration

---

.github/ISSUE_TEMPLATE/release_template.md

This PR adds an issue template to be used as a checklist for upcoming releases.  It is directly copied from the recently added release template in `envisage`.

Create release checklist issue template

---

setup.py

This PR simply bumps the version number in `setup.py` for continued development in advance of the 7.2.0 minor release.

Bump version for continued development (7.3.x)

---

pyface/resource/resource_manager.py
pyface/tests/test_resource_manager.py

Fix #830 (supersede #831)
`importlib_resources.files` requires its input argument to be a Package, where Package is defined [as follows](https://docs.python.org/3/library/importlib.html#importlib.resources.Package):
> The Package type is defined as Union[str, ModuleType]. This means that where the function describes accepting a Package, you can pass in either a string or a module. Module objects must have a resolvable __spec__.submodule_search_locations that is not None.
When Pyface's `ImageResource` is defined in a Python script (e.g. run from the command line), the module  `__name__` is `"__main__"`, which is passed onto `importlib_resources.files` for locating image files. `__main__` fails the requirement on its being a package, hence the error described in the issue.
The test …

Fix loading resource images from a module that is not a package

---

setup.py

[targeting maint/7.2]
This PR bumps the release version and flips the IS_RELEASE flag for the development of the next bug fix release.

Bump release version for the development of 7.2.1

---

pyface/action/action_event.py
pyface/action/api.py
pyface/action/field_action.py
pyface/action/menu_bar_manager.py
pyface/action/menu_manager.py
pyface/action/status_bar_manager.py
pyface/action/tool_bar_manager.py
pyface/action/tool_palette_manager.py
pyface/tasks/action/api.py
pyface/tasks/action/listening_action.py
pyface/tasks/action/schema.py
pyface/tasks/action/schema_addition.py
pyface/tasks/action/task_action.py
pyface/tasks/action/task_action_controller.py
pyface/tasks/action/task_action_manager_builder.py
pyface/tasks/action/task_toggle_group.py
pyface/tasks/action/task_window_toggle_group.py

This PR improves documentation for the following submodules - `pyface.tasks.action` and `pyface.action` submodules.
Specifically, 
- the api modules now have a module docstring, which gets used in the autogenerated API docs
- the in-code comments for traits have been updated such that sphinx picks them up
- two spelling mistakes have been fixed.

Improve documentation for pyface.action and pyface.tasks.action submodules

---

docs/source/conf.py

Using this extension means that API docs now link to source code. See example below which now includes the source button.

Use viewcode sphinx extension

---

etstool.py
setup.py

Closes #845
This PR updates `setup.py` such that package installer will avoid the next release if the Python version is less than 3.6.
Pyface no longer supports Python 2, and CI for Python 3.5 has been removed so it would be difficult to continue its support, Python 3.5 has also reached its end-of-life.
Similar to https://github.com/enthought/traitsui/pull/1436

Declare python_requires to support Python >= 3.6

---

pyface/undo/action/api.py
pyface/undo/api.py

This PR improves the api documentation for `pyface.undo` and `pyface.undo.action` by adding a module docstring to `pyface.undo.api` and `pyface.undo.action.api` which document the classes exposed by the respective API modules.

Improve api docs for pyface.undo and pyface.undo.action

---

pyface/tasks/tasks_application.py
pyface/timer/do_later.py

Not sure if this is the right fix but this is a fix. This PR addresses the following sphinx warnings : 
```
pyface\tasks\tasks_application.py:docstring of pyface.tasks.tasks_application.TaskFactory.factory:3: WARNING: Inline strong start-string without end-string.
pyface\timer\do_later.py:docstring of pyface.timer.do_later.do_later:5: WARNING: Inline strong start-string without end-string.
pyface\timer\do_later.py:docstring of pyface.timer.do_later.do_later:6: WARNING: Inline strong start-string without end-string.
pyface\timer\do_later.py:docstring of pyface.timer.do_later.do_after:7: WARNING: Inline strong start-string without end-string.
pyface\timer\do_later.py:docstring of pyface.timer.do_later.do_after:8: WARNING: Inline strong start-string without end-string.
```
Interpreting the …

Address a few sphinx warnings

---

pyface/tasks/advanced_editor_area_pane.py
pyface/tasks/api.py
pyface/tasks/dock_pane.py
pyface/tasks/editor.py
pyface/tasks/editor_area_pane.py
pyface/tasks/i_dock_pane.py
pyface/tasks/i_editor_area_pane.py
pyface/tasks/split_editor_area_pane.py
pyface/tasks/task.py
pyface/tasks/task_layout.py
pyface/tasks/task_pane.py
pyface/tasks/task_window.py
pyface/tasks/task_window_backend.py
pyface/tasks/task_window_layout.py
pyface/tasks/traits_dock_pane.py
pyface/tasks/traits_editor.py
pyface/tasks/traits_task_pane.py

This PR improves documentation in the `pyface.tasks` submodule in the following ways
- adds a module docstring to `pyface.tasks.api`
- adds a module docstring to the modules that import toolkit-specific classes/implementations
- updates trait comments so that they get picked up by sphinx for api docs.

Improve api documentation in pyface.tasks

---

pyface/qt/__init__.py

Fixes #859 
The code removed should effectively be a no-op on Python 3, since it was configuring `sip` to behave in a Python 3-compatible way.

No longer need to do Python 2 configuration for sip

---

README.rst
etstool.py
pyface/__init__.py
pyface/qt/QtCore.py
pyface/qt/QtGui.py
pyface/qt/QtNetwork.py
pyface/qt/QtOpenGL.py
pyface/qt/QtScript.py
pyface/qt/QtSvg.py
pyface/qt/QtTest.py
pyface/qt/QtWebKit.py
pyface/qt/__init__.py

This does part but not all of #510 - this removes support for PySide, but not PyQt4.
Traits no longer supports any version of Python compatible with the original PySide, so this has been dead code for a while.

Remove support for PySide

---

pyface/__init__.py
pyface/ui/qt4/init.py

Fix #581
First of all, we need a separate distribution for QtWebEngine with PyQt5. This PR expands the `extras_require` so that `pip install pyface[pyqt5]` brings in `PyQtWebEngine`.
After installing `PyQtWebEngine`, importing `QtWebEngineWidgets` after instantiating a QCoreApplication results in an ImportError.  This PR fixes this by trying to import QtWebEngineWidgets before instantiating the QApplication.
All of this has to do with import side effect so it is hard to test. If the test mentioned in #581 is run on its own, it passes on master:
```
$ python -m unittest pyface.ui.qt4.tests.test_qt_imports.TestPyfaceQtImports
.
----------------------------------------------------------------------
Ran 1 test in 0.213s
OK
```
But if it is run after some other tests that have instantiated the …

Fix importing QtWebEngine after toolkit selection

---

pyface/i_widget.py
pyface/tests/test_widget.py
pyface/ui/qt4/widget.py
pyface/ui/wx/widget.py

This PR adds two methods to the base Widget class to set the keyboard focus and to check whether the widget currently has keyboard focus.
This is needed to make it easier to create toolkit-independent TraitsUI Editors that use Pyface widgets.
The tests are skipped on Linux, because there keyboard focus is global, and so a widget doesn't get focus unless the window also has focus/is active, which is hard to guarantee, and is disruptive to development as it prevents the tests from running in the background.
I will open an issue to track the testing of focus on linux.

Expose keyboard focus on Widgets

---

pyface/action/tests/test_action_item.py
pyface/action/tests/test_action_manager.py
pyface/action/tests/test_group.py
pyface/action/tests/test_gui_application_action.py
pyface/action/tests/test_listening_action.py
pyface/action/tests/test_traitsui_widget_action.py
pyface/application.py
pyface/data_view/data_models/tests/test_array_data_model.py
pyface/data_view/tests/test_abstract_value_type.py
pyface/data_view/tests/test_data_view_widget.py
pyface/data_view/value_types/tests/test_constant_value.py
pyface/data_view/value_types/tests/test_editable_value.py
pyface/fields/tests/field_mixin.py
pyface/tasks/tests/test_task_window.py
pyface/tests/test_application.py
pyface/tests/test_beep.py
pyface/tests/test_ui_traits.py
pyface/tests/test_widget.py
pyface/ui/qt4/util/gui_test_assistant.py
pyface/workbench/tests/test_workbench_window.py

With the release of traits 6.2 a section was added to the documentation explicitly requesting users to import from the `.api` modules in traits. See PR https://github.com/enthought/traits/pull/1387
Motivated by this I decided to run through pyface looking for any non api imports from traits.  This PR updates a couple (namely it always imports `UnittestTools` from the `traits.testing.api` and `ETSConfig` from `traitst.etsconfig.api`.
However, I ran into many more examples of traits imports of things not exposed in traits apis.  It is known that this is done but I figured it couldn't hurt to compile a list.  It may be fine to leave them as is, some of these we may want to expose in some traits api, some of them we may not want to be pulling from traits (traits isn't meant to be a storage …

Import from traits apis

---

pyface/ui/wx/data_view/tests/test_data_wrapper.py

Previously running:
```
python etstool.py install 
edm shell -e pyface-test-3.6-pyqt
python -m unittest
```
I was seeing the following test failure:
```
======================================================================
ERROR: pyface.ui.wx.data_view.tests.test_data_wrapper (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyface.ui.wx.data_view.tests.test_data_wrapper
File "/Users/aayres/.edm/envs/pyface-test-3.6-pyqt/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
module = self._get_module_from_name(name)
File "/Users/aayres/.edm/envs/pyface-test-3.6-pyqt/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
__import__(name) …
```

Skip test if wx is not around

---

.travis.yml
pyface/__init__.py

fixes #781 
This PR updates the travis.yml file to require traits 6.1+ not 6.0+.  It also removes a traits version check that prevented data_view test from being run for traits !=6.1.  Not we will want these tests to run on 6.2+ as well.

Stop running CI on traits 6.0

---

examples/application/python_editor/python_editor_task.py
examples/tasks/advanced/example_task.py
examples/tasks/basic/example_task.py
pyface/action/action_item.py
pyface/data_view/data_models/row_table_data_model.py
pyface/data_view/i_data_view_widget.py
pyface/gui_application.py
pyface/tasks/action/dock_pane_toggle_group.py
pyface/tasks/action/task_toggle_group.py
pyface/tasks/action/task_window_toggle_group.py
pyface/tasks/task_window.py
pyface/tasks/tasks_application.py
pyface/tests/test_gui_application.py
pyface/ui/qt4/application_window.py
pyface/ui/qt4/tasks/advanced_editor_area_pane.py
pyface/ui/qt4/tasks/dock_pane.py
pyface/ui/qt4/tasks/editor_area_pane.py
pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/workbench/tests/test_workbench_window_layout.py
pyface/ui/qt4/workbench/workbench_window_layout.py
pyface/ui/wx/application_window.py
pyface/ui/wx/tasks/dock_pane.py
pyface/ui/wx/tasks/editor_area_pane.py
pyface/workbench/action/perspective_menu_manager.py
pyface/workbench/action/set_active_perspective_action.py
pyface/workbench/action/user_perspective_action.py
pyface/workbench/action/view_menu_manager.py
pyface/workbench/debug/debug_view.py
pyface/workbench/workbench_window.py

part of #732 
also part of #637 
This PR incrementally (effectively 1 file per commit) replaces all uses of the `@on_trait_change` decorator with the equivalent form of `@observe`.
Additionally, it removes any explicit use of setting `comparison_mode` as that is no longer needed with traits 6.2
Since traits 6.2 eggs are not on edm yet, I suspect CI will fail(? or at least give the comparison mode warnings), but very soon that will no longer occur. Looks like we also still have CI running with traits6.0 so it does fail
Looks like travis is also having failures that seem to stem from changes made to `i_data_view_widget`.  Those changes were mostly to do with comparison_mode and I did not see them locally, so I'm suspecting they will be resolved with traits 6.2 (🤞 )

Convert on_trait_change decorators to observe decorators

---

docs/source/timer.rst
pyface/action/listening_action.py
pyface/fields/i_combo_field.py
pyface/fields/i_field.py
pyface/fields/i_spin_field.py
pyface/fields/i_text_field.py
pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/action/menu_manager.py
pyface/ui/qt4/action/tool_bar_manager.py
pyface/ui/wx/action/action_item.py
pyface/ui/wx/action/menu_manager.py
pyface/ui/wx/action/tool_bar_manager.py
pyface/ui/wx/grid/grid.py
pyface/ui/wx/grid/trait_grid_model.py
pyface/ui/wx/list_box.py
pyface/ui/wx/preference/preference_dialog.py
pyface/ui/wx/tree/tree.py
pyface/ui/wx/viewer/table_viewer.py
pyface/undo/action/abstract_command_stack_action.py
pyface/workbench/action/toggle_view_visibility_action.py
pyface/wx/grid/grid.py

closes #637 
closes #732 
This PR makes the last round of updates to replace use of `on_trait_change` with `observe`.  With the changes in this PR, `on_trait_change` is no longer present anywhere in the code base.  This PR also makes an update to the documentation section on `timers`.  Please confirm the changes made there are reasonable.  
Note to reviewer, be cautious: some of the code undergoing changes in this PR is not covered by the test suite.  I made some knowingly broken changes and ran the test suite only to find everything still passing. 
This PR also drive by removes some commented out code from the code base.

Convert dynamic on_trait_change to observe part 2

---

docs/source/examples/dict_data_model.py
examples/data_view/column_data_model.py

As of traits 6.2 it is no longer necessary to specify a trait comparison mode of `ComparisonMode.identity`.  This PR simply removes a couple of occurrences of that from examples in the code base.

Remove unneeded setting of comparison_mode

---

pyface/undo/command_stack.py
pyface/undo/tests/test_command_stack.py
pyface/undo/tests/testing_commands.py

Add tests for undo/redo and fix #883 and fix #884 
Not much more.

Fix undo/redo merge bugs

---

setup.py

This PR simply bumps the version number in setup.py for continued development in advance of the 7.3.0 minor release.

Bump version for continued development (7.4.x)

---

pyface/action/listening_action.py

see comment: https://github.com/enthought/pyface/pull/880#discussion_r573969099
This will need a backport before 7.3.0 is officially released!
This PR replaces `trait(_____, optional=True)` with just some if statements to ensure we don't try to hook or unhook things which don't exist.

don't use trait() for extended trait names

---

CHANGES.txt
pyface/action/listening_action.py

[Targeting maint/7.3]
This PR backports a merged PR to the `maint/7.3` branch in preparation for the upcoming release. It also updates the changelog to include the relevant backported PR. Only the last commit which updates the changelog needs to be reviewed (the other has been reviewed already).

Backports for 7.3.0

---

pyface/ui/wx/grid/grid.py

This PR fixes a bug found via the traitsui cron job, see https://github.com/enthought/traitsui/actions/runs/619678526 
Previously we were trying to listen to a trait `read_only_changed` which didn't exist.  we meant to listen to `read_only`.
The new test failures surfaced from the switch from `on_trait_change` to `observe`.  The code was still broken before (we were trying to listen to a non-existent trait), `on_trait_change` was just quiet about it.
Unfortunately the relevant code does not seem to be under test in `pyface` itself?  I did not see any pyface wx test suite failures, but I used pyface from this branch on the traitsUI wx test suite and saw this resolved the errors.  
The allowed wx failures do let things like this slip by though 😬

listen to correct trait name

---

pyface/dock/dock_sizer.py

fixes #901
This commit adds the missing `control` and `name` traits on the `DockItem` class, which other dock classes inherit from.

Add missing trait definitions on DockItem

---

.travis.yml
appveyor.yml

This PR updates EDM to version 3.2.3 (the latest) instead of EDM version 3.0.1.

Use EDM 3.2.3 instead of EDM 3.0.1

---

pyface/ui/wx/action/tool_bar_manager.py

This was missed in the `on_trait_change` to `observe` changes introduced in #880 . The methods were previously receiving
`obj` as an argument to the trait change handler which should have been replaced with `event.object` in #880.
This was discovered when fixing `F821` flake8 failures in pyface.

Handle the events correctly

---

pyface/i_window.py
pyface/message_dialog.py
pyface/ui/qt4/message_dialog.py
pyface/ui/qt4/tests/test_message_dialog.py
pyface/ui/wx/message_dialog.py

Inspired by https://github.com/enthought/traitsui/pull/1546
This PR allows a user to specify the text format they want to use to a message dialog, to help avoid issues like https://github.com/enthought/traitsui/issues/1543
Note, there used to be a `LogText` option, and since qt 5.14 there is a `MarkdownText` option.  I have not added those here to avoid special handling for different Qt versions / because we have not had an explicit use case.  However, if they are needed or wanted, they could be added.

Allow passing a text format to a MessageDialog

---

pyface/action/action.py
pyface/data_view/data_models/tests/test_array_data_model.py
pyface/tasks/action/schema.py
pyface/tasks/tests/test_enaml_dock_pane.py
pyface/tasks/tests/test_enaml_editor.py
pyface/tasks/tests/test_enaml_task_pane.py
pyface/ui/qt4/code_editor/code_widget.py
pyface/ui/qt4/wizard/wizard_page.py
pyface/ui/wx/wizard/wizard_page.py
pyface/wizard/i_wizard_page.py
pyface/workbench/workbench_window.py

This PR fixes F811 flake8 errors - "redefinition of imports"

Fix F811 flake8 errors

---

pyface/util/gui_test_assistant.py
pyface/util/modal_dialog_tester.py
pyface/util/tests/test_gui_test_assistant.py
pyface/util/tests/test_modal_dialog_tester.py

closes #905 
This PR creates modules for `GuiTestAssistant` and `ModalDialogTester` so that they can more easily be imported via 
`from pyface.util.{gui_test_assistant/modal_dialog_tester} import {GuiTestAssistant/ModalDialogTester}`
It is still important to now check if the imported item is `Unimplemented` as these are both currently only supported for qt.
This PR also adds very simply tests to test importing the objects from the modules

Create generic module for GuiTestAssistant and ModalDialogTester

---

pyface/ui/wx/image_button.py

Previously we only did various layout calculations in the `__init__` method.  this ignored the possibility of say starting with `image` as `None` and then setting it later, leading to incorrect layout of things.  See the full saga here:
https://github.com/enthought/traitsui/pull/1566/files#r616858523

fix how/when layout calcs are done in wx ImageButton

---

pyface/base_toolkit.py

closes #927 
Note, that later in the file we were already just directly using `ETSConfig.provisional_toolkit` not `provisional_toolkit` (effectively assuming the try portion of the try...except would succeed).  This PR removes the whole try...except which is now unnecessary.

Remove unnecessary try/except around ETSConfig.provisional_toolkit

---

pyface/base_toolkit.py

closes #930 
`sys._exc_traceback` has been deprecated and was causing an error if running the test suite with `ETS_DEBUG=True`.  This PR replaces it and we no longer see that error.
Unfortunately, running the test suite with `ETS_DEBUG=True` is still not a pretty sight, with numerous errors.  Those can be addressed in separate PRs

replace sys.exc_traceback with sys.exc_info()[2]

---

pyface/ui/qt4/init.py

This PR removes the runtime errors that were being reaised for very old versions of PyQt4 and Qt4, specifically `< 4.1` for PyQt4 and `< 4.2` for Qt4. This is acceptable as the only available versions of PyQt4 on EDM for Python 3 are `>= 4.11`.

Dont complain about old versions of PyQt4 and Qt4

---

pyface/ui/wx/init.py

This PR removes code that was handling wx version < 2.8. Wx less than 2.8 isnt even available via pypi for python 3. Ref https://pypi.org/project/wxPython/#history

Cleanup code handling wx version < 2.8

---

docs/source/conf.py
docs/source/index.rst
docs/source/testing.rst

closes #904
This PR adds a "GUI Testing" section to the documentation describing the `GuiTestAssistant` and `ModalDialogTester`.

Document the GuiTestAssistant and ModalDialogTester

---

docs/source/applications.rst
docs/source/overview.rst
examples/application/hello_world/hello_application.py
examples/application/python_editor/python_editor.py
examples/application_window.py
examples/dialog.py
examples/explorer.py
examples/image_widget.py
examples/mdi_application_window.py
examples/multi_toolbar_window.py
examples/progress_dialog.py
examples/python_editor.py
examples/splash_screen.py
examples/tasks/advanced/python_editor_qt4.py
examples/timer.py
examples/tool_palette.py

This PR updates `super` usage in docs and examples. See related PRs #944 , #945 and #946

Update super usage in docs and examples

---

pyface/__init__.py
pyface/resource/resource_manager.py
pyface/tests/test_image_resource.py

This PR:
- updates the core code to use `importlib.resources.files` in preference to `importlib_resources.files`
- updates the `setup.py` requirements so that `importlib_resources` and `importlib_metadata` aren't installed if they're not needed
Closes #942.

Use importlib.resources.files and importlib.metadata if available

---

pyface/wx/shell.py

Call `__init__` on the right class - `wx.StyledTextCtrl` instead of `wxStyledTextCtrl`.

Its "wx.StyledTextCtrl", not "wxStyledTextCtrl"

---

etstool.py

This PR removes support for the `PyQt` toolkit in the CI utility `etstool.py`. Now that we don't test against `PyQt` on CI anymore (see #949 ), we dont need to support `PyQt` in the `etstool` utility.

Remove PyQt support in etstool CI utility

---

pyface/ui/qt4/util/event_loop_helper.py
pyface/ui/qt4/util/tests/test_event_loop_helper.py

closes #701 
This PR follows the lead of https://github.com/enthought/envisage/pull/301

Make EventLoopHelper expect an IGUI instance

---

pyface/tasks/action/schema.py
pyface/tasks/task_layout.py
pyface/tasks/task_window_layout.py
pyface/timer/i_timer.py
pyface/ui/wx/grid/composite_grid_model.py
pyface/ui/wx/grid/simple_grid_model.py
pyface/ui/wx/grid/trait_grid_model.py

This PR replaces the `Either` trait with the `Union` trait.
> A new Union trait type has been added. This is intended as a simpler replacement for the existing Either trait type, which will eventually be deprecated.
See https://github.com/enthought/traits/releases/tag/6.1.0.
See similar PR in traitsui https://github.com/enthought/traitsui/pull/1581

Replace "Either" trait with "Union"

---

.github/workflows/ets-from-source.yml
.github/workflows/test-with-edm.yml

part of #948 (which can be closed when we drop travis / appveyor)
This PR adds two _nearly_ identical work flows. One of which will run the test suite on every PR using packages from edm, the other which will run the test suite as a cron job using ets packages from source.

Port CI to gh-actions

---

pyface/data_view/data_models/tests/test_array_data_model.py
pyface/ui/qt4/console/console_widget.py

This PR addresses a few deprecation warnings observed using python 3.8 and pyqt5 on the traitsui and pyface test suites.

Address a few deprecation warnings when using python 3.8 and pyqt5

---

examples/tasks/advanced/python_editor_qt4.py
examples/tasks/advanced/python_editor_wx.py
pyface/action/action_item.py
pyface/action/action_manager.py
pyface/action/group.py
pyface/action/listening_action.py
pyface/dock/dock_sizer.py
pyface/dock/tests/test_dock_sizer.py
pyface/ui/qt4/application_window.py

Part of #899 
This PR replaces some of the instances of `_*_changed` static trait listeners with `observe` from the code base.  There are still plenty more that will need to be addressed in follow up PRs.

Update  _*_changed static trait listeners to use traits observe

---

docs/source/fields.rst
pyface/fields/api.py
pyface/fields/i_toggle_field.py
pyface/fields/tests/test_toggle_field.py
pyface/fields/toggle_field.py
pyface/ui/qt4/fields/toggle_field.py
pyface/ui/wx/fields/toggle_field.py

This PR adds additional fields with toggling behaviour: check boxes, radio buttons, and toggle buttons.
The purpose of this functionality is to abstract the common API to permit an eventual refactor of the TraitsUI `BooleanEditor` to allow styles other than checkboxes.

Toggle Fields (CheckBoxField, RadioButtonField, etc.)

---

.github/workflows/ets-from-source.yml
.github/workflows/test-with-edm.yml
etstool.py
pyface/dock/dock_window.py
pyface/dock/dock_window_feature.py
pyface/tasks/task_window.py
pyface/tests/test_widget.py
pyface/tree/node_manager.py
pyface/tree/node_tree.py
pyface/ui/qt4/gui.py
pyface/ui/qt4/heading_text.py
pyface/ui/qt4/tasks/advanced_editor_area_pane.py
pyface/undo/undo_manager.py
pyface/wizard/chained_wizard.py
pyface/wizard/chained_wizard_controller.py
pyface/wizard/wizard_controller.py

Continuation of #954, and therefor part of #899
This PR simply replaces some more `_*_changed` magic named static handlers with observe.

More _changed method updates to observe

---

pyface/ui/qt4/tests/test_qt_imports.py

`pyface.qt.QtScript` is expected to throw a deprecation warning on `PyQt5`/`PySide2`. We refactored the existing test to create a new test that checks for the deprecation warning  while also swallowing the deprecation warning thereby making the test output cleaner.
fixes #582 (the last open item)

Catch deprecation warning thrown by QtScript import in testsuite

---

.github/workflows/ets-from-source.yml
.github/workflows/test-with-edm.yml

This PR updates GitHub Actions CI to use `ubuntu-latest` instead of using an older version of ubuntu. I'm not entirely sure why we were pinning CI to use an older version of ubuntu in the first place - we might just have copied over existing CI configuration from another ETS repository.

Use "ubuntu-latest" in GitHub Actions CI

---

.github/workflows/ets-from-source.yml

This PR makes it possible to manually trigger the cron job - using `workflow_dispatch`. Ref https://github.com/enthought/ets/issues/68

Make it possible to manually trigger cron job

---

pyface/i_heading_text.py
pyface/tests/test_heading_text.py
pyface/ui/qt4/heading_text.py
pyface/ui/wx/heading_text.py

Improvements and fixes for HeadingText:
- aligns Qt _create_control with standard API
- routes creation through create() call
- makes widget creation in init() optional
- deprecates automatic widget creation
- makes appearance of Qt and Wx similar (deprecates background image for wx)
- changes to text are dispatched on the ui thread
- general clean-up and standardization
- better testing
- various other small fixes

HeadingText fixes

---

pyface/i_split_widget.py
pyface/split_panel.py
pyface/tests/test_split_panel.py
pyface/ui/qt4/split_widget.py
pyface/ui/wx/image_button.py
pyface/ui/wx/split_widget.py
pyface/ui_traits.py

Some improvements to the `SplitWidget` class and related classes (particularly `SplitPanel`)
- clean up of traits (including adding an "Orientation" trait)
- deprecate automatic creation of widgets in `SplitPanel.__init__` (part of #729)
- add an `Orientation` trait and use it where applicable

SplitWidget fixes

---

.github/workflows/ets-from-source.yml

This PR sets up the slack notification for the cron job.
I manually triggered the cron job to check that the slack notification gets fired. Ref https://github.com/enthought/pyface/actions/runs/1027257422.
One more step towards https://github.com/enthought/ets/issues/65

Setup slack notification for cron job

---

pyface/api.py
pyface/i_layered_panel.py
pyface/tests/test_layered_panel.py
pyface/ui/qt4/layered_panel.py
pyface/ui/wx/layered_panel.py
pyface/ui/wx/preference/preference_dialog.py
pyface/ui/wx/wizard/wizard.py

This takes the existing wx-only `LayeredPanel` and:
- adds an `ILayeredPanel` interface
- implements the Qt version of it
- adds tests for it
- deprecates autocreation in the `__init__` method
- updates the usage of `LayeredPanel` in `Wizard` and `PreferencesDialog`
It does not attempt to improve the `LayeredPanel` API (eg. by allowing removal of layers, etc.)

Implement ILayeredPanel.

---

pyface/__init__.py
pyface/base_toolkit.py

fixes #952. It removes a deprecated feature from importlib_metadata. See the reference here: https://importlib-metadata.readthedocs.io/en/latest/history.html#v3-9-0.

Remove a deprecated method from `importlib_metadata`

---

pyface/ui/wx/grid/grid.py
pyface/ui/wx/image_button.py
pyface/ui/wx/image_widget.py
pyface/ui/wx/list_box.py
pyface/ui/wx/progress_dialog.py
pyface/ui/wx/tree/tree.py
pyface/ui/wx/viewer/table_viewer.py
pyface/ui/wx/viewer/tree_viewer.py

As discussed in #729 this does the discussed deprecation transforms in the remaining Wx widgets that use that approach.
Most of these widgets have not tests, but they are exercised by the examples.

Deprecate `__init__` methods which create the widget

---

pyface/tests/test_toolkit.py

This was missed in #991 and is needed to fully resolve #952 . The change introduced in this PR removes the deprecation warning raised by `importlib_metadata` from the test run as well.
```
2021-07-16T05:11:29.3287021Z test_core_plugins (pyface.tests.test_toolkit.TestToolkit) ... /home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyqt5/lib/python3.6/site-packages/pyface/tests/test_toolkit.py:36: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
2021-07-16T05:11:29.3290051Z   plugins = {ep.name for ep in entry_points()['pyface.toolkits']}
2021-07-16T05:11:29.3290882Z ok
```

Use the select interface when using entry points

---

pyface/__init__.py
pyface/base_toolkit.py
pyface/tests/test_toolkit.py

This PR adds a compatibility layer to the entry point code to handle the absence of the `select` method on entry points. Additionally, we now rely on the external `importlib_metadata` first and only if that is absent do we rely on `importlib.metadata` from the standard library.
fixes #998 
Note to reviewer : I tested this locally by creating a python 3.9 virtual environment, installing pyface and relevent test dependencies and running the testsuite. On this branch, I don't see the `select`-related test errors that we see on the `master` branch.

Dont rely on the existence of "select" on entry points

---

pyface/api.py
pyface/wx/spreadsheet/default_renderer.py

As per the issue #972 I have added optional import of PILImage and also added it in the miscellaneous section of module doc. Please suggest the changes, if I have done something wrong.

Added PILImage to pyface.api

---

pyface/api.py

This PR explicitly adds a `numpy` import before the `ArrayImage` import to ensure that an `ImportError` is raised instead of a `TraitError`, which will get caught and handled correctly by the `_optional_import` utility.
This was first observed thanks to the cron job - https://github.com/enthought/envisage/runs/3139307870

Explicitly import "numpy" for "ArrayImage" import

---

pyface/tasks/tests/test_action_manager_builder.py
pyface/tasks/tests/test_dock_pane_toggle_group.py
pyface/tasks/tests/test_editor_area_pane.py
pyface/tasks/tests/test_task_layout.py
pyface/tasks/tests/test_topological_sort.py
pyface/ui/qt4/code_editor/tests/test_code_widget.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py
pyface/ui/qt4/tests/test_mimedata.py
pyface/ui/qt4/util/tests/test_modal_dialog_tester.py
pyface/util/tests/test_id_helper.py

This PR removes unnecessary `if __name__ == "__main__"` code blocks. Specifically, this commit removes the `unittest.main()` calls.

Remove unnecessary if name/main code blocks

---

pyface/base_toolkit.py

This PR removes unreachable code from the `find_toolkit` function.

Remove unreachable code

---

.github/ISSUE_TEMPLATE/release_template.md
README.rst
docs/source/conf.py

This PR replaces the use of ``master`` in the repo with ``main`` as the default branch name has been updated.

 Default branch has been renamed from "master" to "main"

---

docs/source/conf.py

This PR removes the unused `extlinks` variable from the sphinx configuration.

Remove unused "extlinks" in sphinx configuration

---

pyface/data_view/i_data_view_widget.py
pyface/fields/i_field.py
pyface/i_widget.py

Initially this does nothing, but it allows `super()` calls in `_create()` methods for widgets which want to do post-creation initialization that respects inheritance.
Updates `IField` and `IDataViewWidget` to take advantage of this.
This is a minor change that permits a number of other things to move forward more naturally.

Add an `_initialize_control()` method to `IWidget`

---

pyface/data_view/i_data_view_widget.py
pyface/data_view/tests/test_data_view_widget.py
pyface/fields/i_field.py
pyface/fields/tests/field_mixin.py
pyface/i_layout_item.py
pyface/i_layout_widget.py
pyface/layout_widget.py
pyface/testing/layout_widget_mixin.py
pyface/testing/widget_mixin.py
pyface/ui/qt4/data_view/data_view_widget.py
pyface/ui/qt4/fields/field.py
pyface/ui/qt4/layout_widget.py
pyface/ui/wx/data_view/data_view_widget.py
pyface/ui/wx/fields/field.py
pyface/ui/wx/layout_widget.py

This adds infrastructure below `IWidget` for widgets that have opinions about sizing; in particular should they be allowed to expand, what weight should they have compared to other widgets when expanding, and are there bounds on how big they can get?  This is useful for widgets which are embedded in layouts and containers.
The PR provides an interface for this, an implementation for both toolkits, and makes this a superclass for `IField` and `IDataViewWidget` for concreteness.  Other widgets will be added tot he system in a separate PR.
This PR is working towards #738 (in that `LayoutWidget` instances are the contents of `IContainers`) and a general layout system for Pyface.  It also is a requirement for being able to directly use Pyface widgets in TraitsUI editors without needing any …

Add `LayoutWidget` class and use it for newer widget classes

---

pyface/tasks/tasks_application.py

We can't assume an arbitrary `IWindow` has an `active_task` to listen to.
Fixes #1025 and fixes #906

Fix observer for `active_task` property.

---

pyface/fields/i_field.py
pyface/fields/tests/field_mixin.py
pyface/i_widget.py
pyface/testing/widget_mixin.py
pyface/ui/qt4/fields/field.py
pyface/ui/qt4/widget.py
pyface/ui/wx/fields/field.py
pyface/ui/wx/widget.py

This is doing essentially the same as #1019 but for context menus, so that now any widget can have a context menu attached to it.
One consequence of this is that `Field` and the testing code for field have become very thin with no toolkit-specific code at all.  This PR is leaving them in that state, but I will open an issue to either do a clean-up or add some meat to them.

Widget context menus

---

etstool.py
flake8_strict.cfg
setup.cfg

This PR also adds a setup.cfg which makes flake8 run cleanly.  There are
things in the clean list that are likely errors and need to be fixed.
This doesn't add flake8 to CI, that should be a separate PR.

Add a flake8 command to etstool.py

---

pyface/workbench/workbench_window.py

fixes #1033
This PR fixes a broken local import in the workbench machinery.

Fix a broken local import

---

pyface/dock/dock_sizer.py
pyface/dock/dock_window.py
pyface/dock/dock_window_feature.py

fixes #1035
This PR fixes more broken local imports. Thanks @mdickinson for finding them.

Fix more broken local imports

---

pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py

Ensure editor tab label and tooltip update correctly when not active; fixes #523.
Includes a small refactor to pull out common code that finds an editor's tabwidget and index in that tabwidget.

Fix SplitEditorAreaPane tab label and tooltip updates

---

pyface/ui/wx/grid/grid.py

Fixes #1039 
This replaces the pattern `Trait(default, None, TraitType)` with `Union(None, TraitType, default_value=default)`, which I think is equivalent.

Remove usages of `Trait()` in codebase

---

examples/chained_wizard.py
examples/wizard.py
pyface/dock/feature_bar.py
pyface/ui/wx/grid/grid.py
pyface/ui/wx/viewer/table_viewer.py
pyface/ui_traits.py

This PR removes deprecated imports of `Color` and `Font` traits from `traits.api` by copying the trait definitions into `pyface.ui_traits` and importing from there.  This does not remove the indirect dependence on TraitsUI, and these traits will likely be removed at some point in the future (or the trait definition moved into Pyface itself).
This is a step towards being able to remove those traits in Traits.
~~Requires #1041~~ merged
Fixes #1040

Remove deprecated `Color` and `Font` trait imports

---

pyface/qt/QtCore.py
pyface/qt/QtGui.py
pyface/qt/QtMultimedia.py
pyface/qt/QtMultimediaWidgets.py
pyface/qt/QtNetwork.py
pyface/qt/QtOpenGL.py
pyface/qt/QtSvg.py
pyface/qt/QtTest.py
pyface/qt/QtWebKit.py
pyface/qt/__init__.py

This allows `QT_API` values for `pyside6` and `pyqt6` and tries to set up submodules appropriately, but no guarantees are made that the backends work with these imports.  The goal of this PR is not perfect support, but to allow Pyface and downstream projects which import from `pyface.qt` to work towards support for Qt6.
Quick testing with PySide6 shows basic functionality, but with a lot of errors due to changes in the API.  This is acceptable for now.

Add experimental support for Qt6

---

docs/source/testing.rst
pyface/ui/qt4/util/gui_test_assistant.py

Fixes #1030 
Adds notes to the docstrings and a warning to the documentation.
(Looks like it might have picked up some spurious whitespace at the end of some lines as well.)

Document issues with transient conditions in `GUITestAssistant`

---

.github/workflows/ets-from-source.yml
.github/workflows/test-with-edm.yml

The cron job recently started hanging for builds on PySide2 / macOS; this seems likely to be related to the GitHub Actions move to macOS 11 for its workers.
This (draft) PR gives half of a fix: it fixes the cron job, but not the PR build. I'll add the other half once I've confirmed that the same problem occurs for the PR build (right now we haven't see the issue on PRs).
xref: https://github.com/enthought/pyface/runs/4558033525?check_suite_focus=true

Fix test hangs with PySide2 / Big Sur

---

pyface/__init__.py

This allows pip-install of Qt6 package dependencies.

Add `extras_require` for Qt6

---

pyface/ui/qt4/font.py

This fixes Qt font conversion functions so that the `family()` of a `QFont` is always included in the families provided to the Pyface `Font`.  It also handles the case where the stretch is not specified; since there is no analogue of this, it is set to the default value of 100.
Fixes #1062.

Fix issues with converting output of QFontDialog to a Font

---

pyface/data_view/i_data_view_widget.py
pyface/fields/i_field.py
pyface/i_widget.py
pyface/testing/widget_mixin.py

Also adds tests for unhooking tooltip observer.  In testing for this, #1067 was discovered, so this includes a fix for that.
Fixes #1063 and #1067.

Ensure context menu observers are unhooked correctly

---

examples/data_view/example_data.py

This is a trivial work-around to make the data view examples more performant.
The `Color` class instances are fairly heavyweight as they have lots of observers; they are intended for the use-case where there are a handful of colors that are shared and mutable.  Before this change, the examples were creating lots of color objects.  We now instead select randomly from a much smaller set.  This dramatically improves start-up time.

Improve data view example performance by limiting colors

---

pyface/tasks/action/task_action_manager_builder.py

Use observers rather than listeners in TaskActionManagerBuilder

---

pyface/tests/test_pil_image.py
pyface/ui/qt4/tests/test_qt_imports.py
pyface/ui/qt4/workbench/tests/test_workbench_window_layout.py

These are fairly basic fixes - just skip when in an incompatible environment - but issues have been opened for more complete fixes.

Fix test failures on EDM and Python 3.8

---

pyface/ui/qt4/code_editor/code_widget.py
pyface/ui/qt4/code_editor/gutters.py

This means that alternate styles/dark mode, etc. should work better for these widgets.
This also changes the default for the code editor to not highlight the current line, as that color should probably have some thought put into it if it is used.  This is a technically non-backward compatible change.

Use colors from widget palette rather than hard-coded

---

pyface/ui/qt4/window.py

Use a weakref to the window that the EventFilter is attached to

---

pyface/ui/qt4/util/image_helpers.py

Fixes #1108 (hopefully).
This stashes a back-reference to a `QImage` when it is used to create a `QPixmap` to ensure that the `QImage` isn't gc-d until we're done with it.
The example from TraitsUI looks like this after the fix:
Unfortunately I don't see a way to create a regression test.
For a reviewer - to replicate set up a Windows/Python3.6/Pyside2 environment with the main branch of TraitsUI and the main branch of Pyface - you should see corruption or get a segfault.  Switching to this branch should fix the problem.

Fix image memory issues

---

pyface/ui/qt4/layout_widget.py
pyface/ui/qt4/tests/test_window.py
pyface/ui/qt4/widget.py
pyface/ui/qt4/window.py

This changes when `hide()` is called to ensure that `QGuiApplication.lastWindowClosed` gets emitted properly.
Fixes #1135

Fix issues with last window close on recent Qt

---

doc-src-requirements.txt
docs/source/conf.py
etstool.py
pyface/__init__.py

This PR does the following: 
- Use the `sphinx_copybutton` extension when building the Sphinx documentation
- Create a `docs` extra for the `pyface` package and add `sphinx-copybutton` as a `docs` dependency along with `enthought-sphinx-theme` and `sphinx`
- Install `sphinx-copybutton` from PyPI when building docs using the `etstool.py` utility.
Ref https://sphinx-copybutton.readthedocs.io/en/latest/

Use the "sphinx-copybutton" extension in documentation

---

pyface/ui/qt4/action/action_item.py

This cycle does not appear to matter on PyQt5, but will persist in PySide2 and PySide6.
This cleanup is required in order to port Mayavi to PySide6, at least without adding more [test skips](https://github.com/enthought/mayavi/blob/a0b9f1ccebdbea6387329655ac0d099d029226d3/tvtk/tests/test_garbage_collection.py#L48) for Mayavi tests that try to determine if forgetting about `DecoratedScene` objects (which make toolbars) doesn't leave cycles.
I could add tests here if we wanted to introduce `gc`-using tests to pyface.

BUG: Remove cycle on cleanup.

---

pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/workbench/split_tab_widget.py
pyface/ui/qt4/workbench/tests/test_split_tab_widget.py
pyface/ui/qt4/workbench/tests/test_workbench_window_layout.py
pyface/ui/qt4/workbench/workbench_window_layout.py

These are some drive-by fixes from issues found when investigating #1117.  None of these actually fix the issue, however.
The changes to the state-saving code don't impact the file format, as no changes are needed for the reader (it can happily ingest both `QByteArray` and `bytes` objects).

Fixes from investigating #1117

---

pyface/base_toolkit.py

This PR updates the `RuntimeError` that appears when no toolkit can be loaded to include the immediate cause of the failure. The goal is to make debugging CI failures along these lines less painful: the `RuntimeError` is often caused by some obscure `ImportError` somewhere down the stack, and with the current code that import error is hidden from view in the CI output.

Include cause of toolkit import failure

---

.github/workflows/test-with-edm.yml
pyface/ui/qt4/action/action_item.py

Over in https://github.com/enthought/mayavi/pull/1180 I am working on VTK 9.2.2 fixes, and I am getting a segfault in CIs during GC:
https://github.com/enthought/mayavi/actions/runs/3222141217/jobs/5270891488
Locally I don't get a segfault but rather a slightly nicer error message:
```
Exceptions caught in Qt event loop:
________________________________________________________________________________
File "/home/larsoner/python/pyface/pyface/ui/qt4/action/action_item.py", line 379, in _qt4_on_destroyed
if hasattr(self.control, "_tool_instance"):
RuntimeError: wrapped C/C++ object of type QAction has been deleted
```
This PR fixes this by catching this `RuntimeError` during `hasattr`. Locally at least the Mayavi tests pass with PyQt5 with this change.

BUG: Safe hasattr for PyQt5

---

pyface/ui/qt4/directory_dialog.py
pyface/ui/qt4/file_dialog.py

This guards against the control having been deleted when we try to get the paths.
Fixes #1158.

Fix DirectoryDialog issue on manual close (vs. cancel)

---

pyface/ui/qt4/code_editor/gutters.py

Fixes #1167 
This should prevent deprecation warnings/errors on more recent versions of Python.

Explicitly convert float to int in gutter widget

---

.github/workflows/ets-from-source.yml
.github/workflows/test-with-edm.yml
etstool.py

This PR fixes CI for Ubuntu 22.04 so that it is back into a working state.  To this end it:
- updates the Qt debian packages
- removes the use of `GabrielBB/xvfb-action@v1` (`xvfb` is in the default 22.04 image)
- removes linux/wx tests as we don't have a compatible wxpython wheel/egg for ubuntu 22.04/wxPython 4.0

CI changes for Ubuntu 22.04

---

pyface/ui/wx/action/status_bar_manager.py
pyface/ui/wx/application_window.py

Another small fix:
Remove the 'parent' argument from 'StatusBarManager.destroy' in the wx backend. The argument is unused, and doesn't match the interface definition.
If you prefer keeping the argument (to not break applications which may pass it explicitly?), I'd propose adding a default `=None`, and emitting a deprecation warning.

Remove 'parent' argument from wx StatusBarManager

---

pyface/ui/qt4/workbench/split_tab_widget.py

Hi,
this should fix https://github.com/enthought/mayavi/issues/1163. As suggested by @corranwebster there the assertion error is replaced by a warning.

Change assert to warning in SplitTabWidget

---

pyface/ui/qt4/code_editor/code_widget.py
pyface/ui/qt4/confirmation_dialog.py
pyface/ui/qt4/console/console_widget.py
pyface/ui/qt4/dialog.py
pyface/ui/qt4/single_choice_dialog.py
pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/util/event_loop_helper.py
pyface/ui/qt4/util/testing.py
pyface/util/guisupport.py

This uses `hasattr` to test whether `exec` is available, which should be all Qt backends except PySide2.
Fixes #1179 and is more complete than #1198

Use `exec` instead of `exec_` where possible for Qt

---

pyproject.toml

I just noticed in passing that `pyface` lists `pyface` as a dependency. This PR fixes that.

Don't list pyface as a dependency of pyface

---

pyface/ui/qt4/gui.py

On Linux, calling `QApplication.thread()` appears to cause an end-of-process segfault. We've been seeing this in the test suites of several applications using the ETS stack.
I've opened an upstream bug report here: https://bugreports.qt.io/browse/PYSIDE-2254
In the meantime, we can avoid _most_ calls to `QApplication.thread` (those not involving a background thread): it's used in a `moveToThread` operation, but we can skip that operation if the current thread _is_ the GUI thread.
This PR makes that change, and adds issue references. I suspect we'll still have the end-of-process segfault problem from code that uses `GUI.invoke_after` / `GUI.invoke_later` / `GUI.set_trait_later` etc. from background threads.

Workaround for end-of-process segfault on Linux

---

pyproject.toml

This PR adds a missing dependency for `importlib_metadata`.
Strictly, we only need `importlib_metadata` for Python < 3.8. But using it for all Python < 3.10 allows us to use a uniform interface when dealing with entry points.

Add missing importlib-metadata dependency

---

pyface/api.py
pyface/tests/test_api.py

Fixes #702
I'd sort of like to have a separate "interfaces API" module (`pyface.interfaces` or `pyface.i_api`?) where these can be imported from without side-effects, but this is good enough for now.

Expose interfaces in `pyface.api`

---

pyface/confirmation_dialog.py
pyface/tests/test_confirmation_dialog.py

Expose more arguments to `confirm` function

---

pyface/ui/qt/gui.py

This has gone back and forth a few times, but right now unhandled exceptions in the `event` handler are causing test failures in TraitsUI on 6.4.3 and this fixes them.

Don't try to dispatch immediately in Qt Gui `_FutureCall`

---

pyface/ui/qt/tests/test_qt4_import_hooks.py
pyface/ui/qt4/__init__.py

This checks against the possibility of the ShadowedModuleFinder being used with different modules (eg. potentially other ETS modules)

Fix problem with multiple matches to shadowed module finder

---

pyface/api.py

This adds a few trait types from pyface.ui_traits which were not in the public API.  It also makes the Font and Color classes visible, for consistency.
Fixes #1071

Expose more ui traits in Pyface API

---

pyface/qt/QtCore.py
pyface/qt/QtGui.py
pyface/qt/QtOpenGL.py
pyface/qt/QtOpenGLWidgets.py
pyface/qt/QtScript.py
pyface/qt/QtSvg.py
pyface/qt/QtSvgWidgets.py
pyface/qt/QtTest.py
pyface/qt/QtWebKit.py
pyface/qt/QtWidgets.py
pyface/qt/__init__.py
pyface/ui/qt/code_editor/code_widget.py
pyface/ui/qt/data_view/data_view_widget.py
pyface/ui/qt/tests/test_qt_imports.py
pyface/ui/qt/workbench/split_tab_widget.py

In particular this includes:
- removing PyQt4 support (PySide is long-gone), but this means no more Qt4 (Fixes #510)
- `QtSvgWidgets`, and backwards compatibility imports in QtSvg on Qt6 platforms (Fixes #1235)
- `QtWidgets` is now available, and we should probably shift imports there instead of QtGui over time (but not in this PR) (work towards #1052)

Update Qt APIs to be more Qt5/Qt6-ish

---

.github/actions/install-qt-support/action.yml
etstool.py
pyface/api.py
pyface/tests/test_api.py
pyface/tests/test_array_image.py

This fixes an issue seen in TraitsUI bleeding-edge tests.

Import optional imports from relative module rather than toolkit

---

.github/dependabot.yml
.github/workflows/test-docs-with-edm.yml

This PR updates the GitHub Actions upload-artifact action used in the documentation build workflow from v3 to v4. This should get the documentation build running again.
I've also added a dependabot config, to help us keep actions up to date where necessary.

Update the upload-artifact version

---

pyface/tests/test_pil_image.py

PIL removed support for Qt 5 in https://github.com/python-pillow/Pillow/pull/8159. This PR skips the `TestPILImage` tests on Qt 5.
Related: https://github.com/enthought/pyface/issues/1255

Skip PILImage tests on Qt5

---

.github/workflows/run-tests.yml

The PySide2 wheels available on PyPI do not support Apple Silicon, so now that the `macos-latest` GitHub runner is Apple Silicon-based, we need to exclude the `macos-latest` / `pyside2` combination from our test workflow.

Don't test with PySide2 and Apple Silicon

---

pyface/tasks/tests/test_tasks_application.py
pyface/tests/test_gui_application.py

This PR updates several tests to avoid a race condition. The relevant tests are doing a `self.gui.invoke_after(1000, app.exit)` before doing `app.run()`, and encountering a situation where `app.exit` is being executed _before_ `app.gui` is set, resulting in a test suite hang. 
Closes #1257

Fix race conditions in some tests

---

.github/workflows/ets-from-source.yml
.github/workflows/test-docs-with-edm.yml
.github/workflows/test-with-edm.yml

This PR updates the EDM version used in test workflows to the most recent version, EDM 4.1.1.
It also updates the `setup-edm-action` to `v4.1`: the `v4` version doesn't know about the new URLs for recent EDMs.
Finally, we also remove `macos-latest` from the test matrix, since we don't currently have all the necessary EDM packages available on Apple Silicon (and the current workflow is only working with Python 3.8, where an Apple Silicon runtime won't be available).

Update EDM version used in test workflows

---

.github/workflows/ets-from-source.yml
.github/workflows/run-style-checks.yml
.github/workflows/run-tests.yml
.github/workflows/test-docs-with-edm.yml
.github/workflows/test-with-edm.yml

Our `ets-from-source` workflow is currently failing, for the simple and shallow reason that we're not currently in a position to run EDM-based tests on macOS/ARM (missing runtime for Python 3.8; missing dependencies for Python 3.11). This PR removes `macos-latest` from the test matrix, and makes a couple of other drive-by cleanups.

Remove macos-latest from ets-from-source workflow
