enthought/pyface

docs/source/conf.py
setup.py

This is the PR for the 4.5.0 release of Pyface.

4.5.0 Release

---

setup.py

Bump version number and set release to false.

Post-4.5.0-Release Version Bump

---

pyface/ui/qt4/code_editor/pygments_highlighter.py

Changes same as done in ipython project
https://github.com/ipython/ipython/pull/6878
(IPython's highlighter is same as this)

Make pygments highlighter compatible with pygments 2

---

CHANGES.txt
pyface/ui/qt4/code_editor/pygments_highlighter.py

Backport of #130 to the 4.5 maintenance branch.  I'll add a changelog entry once this PR has a number. :-)

Make highlighter compatible with Pygments 2

---

CHANGES.txt
MANIFEST.in

Fix MANIFEST.in on maintenance branch

---

.coveragerc
.travis.yml
pyface/tasks/tests/test_dock_pane_toggle_group.py
pyface/tasks/tests/test_editor_area_pane.py
pyface/tasks/tests/test_enaml_dock_pane.py
pyface/tasks/tests/test_enaml_editor.py
pyface/tasks/tests/test_enaml_task_pane.py

This PR adds travis-ci integration. Tests are  run under both qt and wx. Coverage report is collected on codecov.io

Add travis-ci

---

.coveragerc
.travis.yml
pyface/tasks/tests/test_dock_pane_toggle_group.py
pyface/tasks/tests/test_editor_area_pane.py
pyface/tasks/tests/test_enaml_dock_pane.py
pyface/tasks/tests/test_enaml_editor.py
pyface/tasks/tests/test_enaml_task_pane.py

This is a version of #134 for 4.5.x maintenance branch.

Add travis-ci to maintenance branch

---

README.rst
docs/source/index.rst
setup.py

Simple fixes for setup.py and documentation.

Fix project docs and setup

---

setup.py

Maintenance release & version bump.

4.5.1 Release

---

.travis.yml
CHANGES.txt
README.rst
pyface/__init__.py
pyface/tests/test_toolkit.py
pyface/toolkit.py
pyface/ui/null/tests/bad_import.py
pyface/ui/qt4/python_editor.py
pyface/ui/qt4/tests/bad_import.py
pyface/ui/wx/tests/bad_import.py

Fix Qt4 python editor imports and toolkit import logic (maintenance)

---

README.rst
docs/source/index.rst
pyface/toolkit.py

4.5.x maintenance branch version of #149.

Deprecate wx toolkit default maintenance

---

.travis.yml

running the tests in travis-ci now takes just under a minute.

Use travis-ci containers

---

.travis.yml

Use travis ci containers maintenance

---

appveyor-install.cmd
appveyor-test.cmd
appveyor.yml

Maintenance appveyor support

---

pyface/ui/qt4/tasks/main_window_layout.py
pyface/ui/qt4/tasks/task_window_backend.py

Fix task window layout running after control destroyed (maintenance branch)

---

CHANGES.txt
setup.py

Release branch for Pyface 4.5.2

Release 4.5.2

---

dev_requirements.txt

Use traitsui master instead of Python 3 branch.

Use TraitsUI master for Travis CI

---

pyface/dock/idockable.py
pyface/i_image_resource.py
pyface/ui/qt4/console/console_widget.py
pyface/ui/qt4/init.py
pyface/ui/qt4/workbench/split_tab_widget.py
pyface/ui/wx/init.py
pyface/workbench/action/perspective_menu_manager.py
pyface/workbench/action/view_menu_manager.py
pyface/workbench/workbench.py
pyface/wx/spreadsheet/default_renderer.py

The changes should be compatible with Python 2.

Some miscellaneous Python3 fixes.

---

examples/chained_wizard.py
examples/menu_manager.py
examples/progress_dialog.py
examples/python_editor.py
examples/splash_screen.py
examples/timer.py
examples/wizard.py
examples/workbench/run.py
pyface/dock/idockable.py
pyface/i_image_resource.py
pyface/ui/qt4/console/console_widget.py
pyface/ui/qt4/init.py
pyface/ui/qt4/python_editor.py
pyface/ui/qt4/workbench/split_tab_widget.py
pyface/ui/wx/init.py
pyface/workbench/action/perspective_menu_manager.py
pyface/workbench/action/view_menu_manager.py
pyface/workbench/user_perspective_manager.py
pyface/workbench/workbench.py
pyface/wx/spreadsheet/default_renderer.py
setup.py

Some examples are Wx specific, so we won't port those, but we would like to get everything else working if we can.
Builds on #162.

Ensure examples work in Python3

---

pyface/ui/wx/application_window.py
pyface/ui/wx/init.py
pyface/ui/wx/ipython_widget.py
pyface/ui/wx/python_shell.py

Merged version of #115 
Will see if I can get tests turned on for wxPython 3.0 as well before merging.

Fixes for wxPython 3.0

---

pyface/ui/wx/application_window.py
pyface/ui/wx/init.py
pyface/ui/wx/ipython_widget.py
pyface/ui/wx/python_shell.py

This is the results of my first look at compatibility testing, there are likely still more changes that need to be made. I just wanted to get this PR created for now in case others would like to contribute to it.
WIP, don't merge yet. More to come as free time allows...

Fixes and updates for wxPython 3.0.x compatibility

---

CHANGES.txt
appveyor-install.cmd
setup.py

Update CHANGES.txt and version numbers for 5.0.0 release.
This is not ready for merge yet (release flag is not set).

Release 5.0.0

---

pyface/i_progress_dialog.py
pyface/ui/qt4/progress_dialog.py
pyface/ui/qt4/tests/test_progress_dialog.py
pyface/ui/wx/progress_dialog.py

Since #176 was merged, this seemed an appropriate time to beef up the tests for the `ProgressDialog` and clean-up the code somewhat.

Progress Dialog Cleanup

---

pyface/tests/test_application_window.py
pyface/ui/wx/application_window.py

I think this is the root cause of https://github.com/enthought/traitsui/issues/257
Also cleaned up the tests to do a proper close.

Fix double UnInit of AUI in ApplicationWindow under Wx

---

pyface/tests/test_application_window.py
pyface/ui/wx/application_window.py

Maintenance branch version of #184

Fix double UnInit of AUI in ApplicationWindow under Wx.

---

pyface/ui/qt4/progress_dialog.py

FIX: bug in ProgressDialog timer labels

---

pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py

PR against #203 branch
@mdickinson what do you think if this?

Add a test for #203

---

pyface/ui/qt4/code_editor/code_widget.py
pyface/ui/qt4/code_editor/tests/test_code_widget.py

Fixes https://github.com/enthought/traitsui/issues/264

Bug: Readonly CodeEditor allowed adding newlines in view

---

docs/source/index.rst

I looked for this information in pyface and could not find it.
Turns out it was in traitsui, but I think it should be present in
both for convenience.

Added documentation about toolkit selection.

---

docs/source/overview.rst

Update docs to clarify the state of Workbench and Tasks

---

pyface/resource/resource_path.py
pyface/ui/wx/confirmation_dialog.py
pyface/ui/wx/dialog.py

Here are a few changes that are not related to adding tasks support for wx. The tasks support will be a much larger pull request so I wanted to isolate the changes that don't depend on tasks.

pyface fixes not dependent on tasks

---

.travis.yml

Fix a simple typo.  Didn't appear to be affecting tests.

Fix spelling in travis.yml

---

pyface/ui/wx/python_editor.py

See enthought/traitsui#297 and enthought/traitsui#300

Replace 'file' with 'open' for Python 3 compatibility.

---

docs/source/index.rst

See https://github.com/enthought/traits/pull/326.  Should wait until that is merged.

Remove -toolkit references from docs

---

appveyor-install.cmd

Use master branch of traitsui for appveyor

---

pyface/ui/qt4/tasks/advanced_editor_area_pane.py

Do not pass cmp kwarg to sort

---

.travis.yml
MANIFEST.in
ci-src-requirements.txt
pyface/i_progress_dialog.py
pyface/tests/test_progress_dialog.py
pyface/ui/qt4/mimedata.py
pyface/ui/wx/init.py
setup.py
tasks.py
travis_ci_bootstrap_edm.sh

Same idea as https://github.com/enthought/traitsui/pull/321.  Also fixes #235 as part of getting tests to run successfully.
Can't currently test with "null" backend.

EDM-based tests

---

appveyor-install.cmd

Hopefully this should fix the issues we are having right now with the Appveyor tests.

Uninstall stray pyface installed by traitsui

---

examples/tasks/advanced/python_editor_qt4.py
pyface/ui/qt4/about_dialog.py
pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/dialog.py
pyface/ui/qt4/progress_dialog.py
pyface/ui/qt4/python_editor.py
pyface/ui/qt4/timer/do_later.py
pyface/ui/qt4/timer/timer.py
pyface/ui/qt4/wizard/wizard.py
pyface/ui/qt4/wizard/wizard_page.py
pyface/ui/qt4/workbench/split_tab_widget.py
pyface/ui/qt4/workbench/workbench_window_layout.py

This is a fairly mechanical change.  The hope is that this will help resolve #245, since old-style signals and slots has been implicated in some of the problems.

Remove old-style signals and slots

---

examples/dialog.py
pyface/api.py
pyface/i_single_choice_dialog.py
pyface/single_choice_dialog.py
pyface/tests/test_single_choice_dialog.py
pyface/ui/qt4/single_choice_dialog.py
pyface/ui/wx/single_choice_dialog.py

Add a Qt version of the single-choice dialog window that already exists for Wx.

Qt single choice dialog

---

pyface/ui/wx/grid/grid.py
pyface/ui/wx/grid/trait_grid_cell_adapter.py
pyface/ui/wx/workbench/workbench_window_layout.py
pyface/workbench/traits_ui_editor.py
pyface/workbench/traits_ui_view.py
pyface/wx/drag_and_drop.py

This PR removes a handful more TraitsUI dependencies from within Pyface, either pulling functionality into Pyface, or making the imports optional in a reasonable way.

More TraitsUI cleanup

---

.travis.yml
pyface/tests/test_confirmation_dialog.py
pyface/tests/test_message_dialog.py
pyface/ui/qt4/directory_dialog.py
pyface/ui/qt4/image_cache.py
pyface/ui/qt4/tests/test_progress_dialog.py
pyface/ui/qt4/util/modal_dialog_tester.py

Breaking out into separate PR to reduce noise.  We are at point of experimentation for what works and doesn't in Travis CI environment.

Fix tests on Qt5

---

pyface/ui/qt4/workbench/split_tab_widget.py
pyface/ui/qt4/workbench/workbench_window_layout.py

@corranwebster Fixes leftover bug from #256

BUG: Restore ad hoc signals in SplitTabWidget.

---

pyface/base_toolkit.py
pyface/toolkit.py
pyface/ui/wx/action/action_item.py

Fixed a few minor bugs when using wx

Fixes for a few small issues when using wx

---

pyface/ui/qt4/gui.py
pyface/ui/qt4/tests/test_gui.py

Fix GUI.do_trait_later to not sendPostedEvents

---

pyface/qt/QtWebKit.py

Add missing import for PyQt5 compatibility.

Add missing QtWebkit import for PyQt5 compatibility

---

pyface/qt/__init__.py

Give better error messages about PyQt API versions

---

pyface/dock/dock_sizer.py
pyface/ui/wx/file_dialog.py
pyface/ui/wx/grid/grid.py
pyface/ui/wx/gui.py
pyface/ui/wx/image_button.py
pyface/ui/wx/image_widget.py
pyface/ui/wx/system_metrics.py
pyface/ui/wx/window.py

Running Mayavi with the latest wxPython or older versions like here
fails: https://travis-ci.org/enthought/mayavi/jobs/337913143
with wxPython 2.8.x.  Looks like it should be `control.Bind`.

BUG: Fixing use of `control.bind`.

---

examples/dialog.py
examples/explorer.py
examples/node_tree.py
examples/tasks/advanced/python_editor.py
examples/tasks/advanced/python_editor_qt4.py
examples/traitsui_window.py
examples/tree.py
examples/tree_viewer.py
pyface/base_toolkit.py
pyface/qt/QtWebKit.py
pyface/ui/qt4/console/console_widget.py

Some fixes based on problems detected while running through Pyface and TraitsUI examples.

Fixes from TraitsUI examples

---

.travis.yml
appveyor.yml
etstool.py
pyface/qt/QtCore.py
pyface/qt/QtGui.py
pyface/qt/QtNetwork.py
pyface/qt/QtOpenGL.py
pyface/qt/QtScript.py
pyface/qt/QtSvg.py
pyface/qt/QtTest.py
pyface/qt/QtWebKit.py
pyface/qt/__init__.py

Add PySide2 support to the Qt backend.

Basic PySide2 support

---

pyface/i_python_shell.py
pyface/tests/test_python_shell.py
pyface/ui/qt4/console/history_console_widget.py
pyface/ui/qt4/python_shell.py
pyface/ui/wx/python_shell.py

Add API to get and set history on PythonShell widget

---

pyface/image/image.py

BUG: Use open() instead of file().

---

.coveragerc
.travis.yml
etstool.py

Codecov isn't properly combining across Travis runs.
Also fixes #343 as I needed it to test that coverage combine worked.

Fix Codecov

---

etstool.py
pyface/gui_application.py
pyface/i_window.py
pyface/tasks/task_window.py
pyface/tests/test_application.py
pyface/tests/test_gui_application.py
pyface/tests/test_message_dialog.py
pyface/tests/test_single_choice_dialog.py
pyface/tests/test_window.py
pyface/ui/qt4/window.py
pyface/ui/wx/window.py

Following on from #334, this is a stripped down `GUIAplication` from #285.

GUI Application

---

pyface/ui/qt4/progress_dialog.py

See: https://github.com/enthought/traitsui/issues/487

Add missing create_percent method

---

pyface/timer/api.py

Fix pyface.timer.api imports

---

pyface/qt/__init__.py

Add top-level flags for whether we have Qt4 and Qt5.

Add flags which indicate which Qt version is in use

---

docs/source/fields.rst
docs/source/overview.rst
docs/source/submodules.rst

Should do a regeneration of the API docs as well.

[WIP] Add docs for fields and widget actions

---

CHANGES.txt
setup.py

Release 6.1.0

---

pyface/timer/do_later.py
pyface/timer/tests/test_do_later.py

Fixes #388.  With a regression test, even.

Fix API of DoLaterTimer to match earlier versions

---

pyface/util/fix_introspect_bug.py

This is an improved version of #383.

Remove use of cmp in fix_introspect_bug

---

docs/source/overview.rst

Maintenance branch version of #384.

Don't compare integers using 'is' (maintenance)

---

pyface/dock/api.py
pyface/dock/dock_sizer.py
pyface/dock/dock_window.py
pyface/dock/dock_window_feature.py
pyface/dock/dock_window_shell.py
pyface/dock/feature_bar.py
pyface/dock/feature_tool.py
pyface/ui/wx/application_window.py
pyface/ui/wx/window.py

Fix Wx local imports (Maintenance)

---

.travis.yml
appveyor.yml

Adding to th branches watched by the CI tools.

Run CI on 6.1 maintenance branch

---

.travis.yml
pyface/qt/QtScript.py
pyface/qt/QtWebKit.py
pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/tests/test_qt_imports.py
pyface/util/fix_introspect_bug.py

Omnibus PR fro remaining backported bugfixes from master.

Backported bugfixes

---

pyface/tests/test_ui_traits.py
pyface/ui_traits.py

Fixes #403 
Can't replicate in a regression test, unfortunately, but have added tests which should specifically exercise the line in question.

Update deprecated traits 'get' command

---

pyface/tests/test_ui_traits.py
pyface/ui_traits.py

Update deprecated traits 'get' command (#404)

---

CHANGES.txt

Incorporates 6.1.1 changelog into master changelog.

Update change log

---

pyface/ui/qt4/python_shell.py

This seems like an error from Python-2 specific code.

BUG: fix error during tab completion on shell.

---

pyface/timer/i_timer.py
pyface/timer/tests/test_timer.py
pyface/timer/timer.py

Added tests for old Timer API, fixes to methods and properties to make sure everything works as advertised.
Fixes #408.

Fix legacy timer api issues

---

pyface/timer/tests/test_timer.py

Sorry this is a minor change I should have made in my last PR.

Fix minor issue in test.

---

pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py

#422 lacked a regression test. Here it is.

Regression test for split editor area merge messages

---

docs/source/index.rst
examples/application/python_editor/python_editor_task.py
examples/dock/dock_test3.py
pyface/dock/dock_window_feature.py
pyface/tasks/action/schema.py
pyface/tasks/i_editor.py
pyface/tasks/i_task_pane.py
pyface/tasks/i_task_window_backend.py
pyface/timer/i_timer.py
pyface/timer/tests/test_timer.py
pyface/timer/timer.py
pyface/ui/qt4/gui.py
pyface/ui/qt4/python_shell.py
pyface/ui/qt4/tasks/split_editor_area_pane.py
pyface/ui/qt4/tasks/tests/test_split_editor_area_pane.py
pyface/ui/wx/gui.py
pyface/workbench/action/view_chooser.py
pyface/workbench/action/view_menu_manager.py

This is all PRs from master since the 6.1.1 release except #419 which is a new feature.

Backport bugfixes into 6.1 maintenance branch

---

CHANGES.txt
setup.py

Release 6.1.2

---

.travis.yml
appveyor.yml

Add wxpython to tests that have to pass CI.

Require wxPython tests to pass

---

etstool.py

Don't install traits with EDM

---

pyface/resource/resource_manager.py
pyface/tests/test_resource_manager.py

Fixes #475 
Change collections.Sequence to collections.abc.Sequence

Use collections.abc.Sequence instead of collections.Sequence

---

pyface/ui/qt4/util/event_loop_helper.py
pyface/ui/qt4/util/testing.py

Avoid deprecation warning by rounding arg to `setInterval` to an int.

---

pyface/ui/wx/grid/grid.py
pyface/ui/wx/grid/trait_grid_cell_adapter.py
pyface/ui/wx/image_button.py
pyface/wx/grid/grid.py
pyface/wx/spreadsheet/abstract_grid_view.py

Mostly binding changes that were missed by automated scripts.

Fixes for wxpython4 changes

---

.travis.yml

More linux dependencies needed

---

pyface/ui/qt4/util/image_helpers.py
pyface/ui/qt4/util/tests/test_image_helpers.py

Add helper functions to convert between QImages and numpy arrays.

Qt image helpers

---

ci-src-requirements.txt

Stay testing against released Traits versions, at least for now.

Switch back to master branch of TraitsUI for testing

---

setup.py

Added long_description_content_type

---

docs/source/index.rst
pyface/__init__.py
pyface/resource/__init__.py

- Remove references to "Traits visualization" - it should be TraitsUI
- Remove references to TraitsGUI, it should also be TraitsUI

Fix the index page of docs

---

etstool.py
pyface/ui/qt4/code_editor/tests/test_code_widget.py
pyface/ui/qt4/workbench/tests/test_workbench_window_layout.py
pyface/workbench/tests/test_workbench_window.py

Use mock from unittest

---

etstool.py

This is a very simple PR to fix some typos in etstool.py (one was from me, oops).

Fix typo/spelling mistake in etstool

---

setup.py

This implements a suggestion made in PR #617

converting long_description to use a context manager

---

pyface/data_view/data_models/array_data_model.py
pyface/data_view/data_models/tests/test_array_data_model.py

Fix errors when changing ArrayDataModel value types with empty data

---

examples/data_view/column_example.py

Images were not showing up correctly.

Missed a change to image API in data view column example

---

pyface/tests/test_ui_traits.py
pyface/ui_traits.py

This provides a convenience trait `PyfaceColor` that casts tuples, strings, etc to `Color`.
This trait is intended to eventually be a replacement for the existing `Color` trait from TraitsUI.

Add a PyfaceColor trait to pyface.ui_traits

---

setup.py

This step should have been done prior to branching off from the master branch to create the maintenance branch. Luckily, no other PRs have been merged yet since the commit used for the maintenance branch.

Bump version for continuous development (7.2.x)

---

CHANGES.txt

Two recently merged PRs to be included in release 7.1.0 were not mentioned in the Changelog. This PR fixes that.
[Targeting the maintenance branch of 7.1]

Add mentions of the two recent PRs to Changelog

---

docs/source/conf.py

Skip load_tests in API documentation

---

etstool.py

Skip tests packages in API documentation

---

etstool.py

See similar PR in traitsui https://github.com/enthought/traitsui/pull/1369
I have tested this locally and it works as expected (the docs get built, with a bunch of warnings).
fixes #564

FIX docs click command to work on windows

---

pyface/action/action_controller.py
pyface/application.py
pyface/base_toolkit.py
pyface/data_view/abstract_value_type.py
pyface/data_view/value_types/editable_value.py
pyface/i_widget.py
pyface/tasks/i_editor_area_pane.py
pyface/timer/do_later.py
pyface/toolkit.py
pyface/ui_traits.py

Addresses most of the warnings reported in #563 
This PR addresses most of the sphinx documentation warnings reported when building the documentation.

Address sphinx warnings when building docs

---

pyface/tests/test_widget.py
pyface/ui/qt4/widget.py

This fixes #806 and fixes #786 along the lines of the suggested work-arounds from those issues.
Tests for expected behaviour are included.

Fix Qt widget visibility

---

CHANGES.txt

[Targeting maint/7.2]
This PR simply updates the changelog for the 7.2.0 release

update changelog for 7.2.0 release

---

setup.py

This PR simply sets `IS_RELEASED` to True, and `PRERELEASE` to "rc1".

Release Candidate 7.2.0rc1

---

pyface/action/action_manager.py

This PR removes some commented out/dead code in `ActionManager.__init__`

Remove commented out/dead code in ActionManager

---

setup.py

The commit from this PR will be tagged as the release.

Pyface Release 7.2.0

---

CHANGES.txt

This PR simply updates the changelog to match the updates that were made on maint/7.2.

Update Changelog after release of 7.2.0

---

CHANGES.txt

This PR updates the changelog in preparation for the upcoming 7.3.0 minor release.

Update changelog for 7.3.0 release

---

setup.py

[targeting maint/7.3]
This PR simply sets `IS_RELEASED` to True, and `PRERELEASE` to "rc1".

Release Candidate 7.3.0rc1

---

pyface/action/api.py
pyface/preference/preference_dialog.py
pyface/tasks/api.py

This PR simply fixes a couple of warnings that occur when building the documentation. One of them was caused by an actual bug in the code (seems like a copy-pasta error)

Fix some doc warnings

---

setup.py

The commit from this PR will be tagged as the release.

Pyface Release 7.3.0

---

setup.py

[targeting maint/7.3]
This PR bumps the release version and flips the IS_RELEASE flag for the development of the next bug fix release.

Bump release version for the development of 7.3.1

---

CHANGES.txt

This PR simply updates the changelog to match the updates that were made on maint/7.3.

Update Changelog after release of 7.3.0

---

pyface/api.py
pyface/data_view/api.py
pyface/data_view/data_models/api.py
pyface/data_view/exporters/api.py
pyface/data_view/value_types/api.py
pyface/dock/api.py
pyface/fields/api.py
pyface/fields/i_combo_field.py
pyface/fields/i_field.py
pyface/preference/api.py
pyface/resource/api.py
pyface/timer/api.py
pyface/tree/api.py
pyface/viewer/api.py
pyface/viewer/tree_item.py
pyface/wizard/api.py

This PR updates the module docstrings for a number of `api` submodules to improve the autogenerated API documentation.

Update module docstrings for API documentation

---

pyface/dock/dock_sizer.py
pyface/resource/resource_manager.py
pyface/wx/image.py
pyface/wx/python_stc.py

This PR fixes the E401 flake8 errors - multiple imports on the same line.

Fix E401 flake8 errors

---

pyface/tree/tree_model.py
pyface/viewer/default_tree_content_provider.py
pyface/viewer/tree_content_provider.py
pyface/wx/grid/grid.py

This PR fixes the F821 flake8 errors - "undefined names".

Fix F821 flake8 errors

---

pyface/base_toolkit.py
pyface/workbench/workbench_window.py

This fixes E713 flake8 errors - "a not in b, not not a in b"

Fix E713 flake8 errors

---

.travis.yml
appveyor.yml

Part of https://github.com/enthought/ets/issues/57
This PR removes testing with pyqt4 from CI

Remove testing on pyqt4 from CI

---

pyface/util/event_loop_helper.py
pyface/util/tests/test_event_loop_helper.py

This PR follows the same approach as #926, only this time for the `EventLoopHelper`.
Motivated by this comment:
https://github.com/enthought/pyface/pull/953#discussion_r653537939

Create generic module for EventLoopHelper

---

docs/source/image_types.rst
docs/source/index.rst

This documents `IImage` and related classes.

Add some basic documentation about image types

---

pyface/wx/spreadsheet/default_renderer.py

Updated deprecated font-related aliases on line 34

Updated Line 34 as per #940

---

docs/source/image_types.rst

This provides an overview of the image library code and how to use it to get `ImageResources`.

Add some documentation about `ImageLibrary`

---

pyface/wx/shell.py

Import from wx.py instead of PyCrust.
Fixes #1037.

Fixes wx shell imports

---

pyface/ui/wx/color_dialog.py
pyface/util/tests/test_color_parser.py

Also add missing copyright header on color parser test file.
Fixes #1061

Fixes for wx color dialog

---

CHANGES.txt

May need some tweaking before release, but this covers everything, I think.

Draft of changelog for Release 7.4.0

---

README.rst
docs/source/index.rst
docs/source/toolkits.rst

Ensuring descriptions are valid for current state of toolkits for release.
Includes one drive-by fix of Sphinx markup.

Update toolkit support discussion and readme

---

CHANGES.txt

These should be the last before the release, unless we find some show-stopper.

A handful more changelog updates

---

setup.py

This is the 7.4.0 release branch.

Release 7.4.0

---

setup.py

This moves main to non-released 7.5.0.

Post-7.4.0 release version bump

---

pyface/ui/qt4/util/image_helpers.py

This is a copy of #1109 moved to the maintenance branch for 7.4.

Fix image memory issues (maintenance branch)

---

CHANGES.txt
setup.py

This is the 7.4.1 release - it updates the change log and sets the release flag.

Release 7.4.1

---

setup.py

Post-release version bump for 7.4 maintenance branch

---

CHANGES.txt

Updates to the changelog from the 7.4.1 release targeting the main branch.

Update the changelog for the 7.4.1 release (main branch)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/release_template.md

This updates the release issue template, as well as adding templates for bug reports and feature requests.

Update issue templates

---

pyface/ui/qt4/widget.py

Map menu coordinates to global before showing

---

pyface/ui/qt4/console/console_widget.py
pyface/ui/qt4/console/tests/test_console_widget.py

Fix Qt ConsoleWidget for Qt6

---

.github/workflows/publish-on-pypi.yml
CHANGES.txt
doc-src-requirements.txt
docs/source/conf.py
pyface/__init__.py
pyface/i_about_dialog.py
pyface/i_application_window.py
pyface/qt/QtOpenGL.py
pyface/tests/test_about_dialog.py
pyface/ui/qt4/about_dialog.py
pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/action/status_bar_manager.py
pyface/ui/qt4/application_window.py
pyface/ui/qt4/console/console_widget.py
pyface/ui/qt4/console/tests/test_console_widget.py
pyface/ui/qt4/font.py
pyface/ui/qt4/layout_widget.py
pyface/ui/qt4/tests/test_qt_imports.py
pyface/ui/qt4/tests/test_window.py
pyface/ui/qt4/widget.py
pyface/ui/qt4/window.py
pyface/ui/wx/about_dialog.py
pyface/ui/wx/action/status_bar_manager.py
pyface/ui/wx/application_window.py
pyface/ui/wx/font.py

This is ready to go - all target issues are fixed and backported.
Fixes #1127

Backport bugfixes for 7.4.2 release

---

CHANGES.txt
pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/workbench/split_tab_widget.py
pyface/ui/qt4/workbench/tests/test_split_tab_widget.py
pyface/ui/qt4/workbench/tests/test_workbench_window_layout.py
pyface/ui/qt4/workbench/workbench_window_layout.py

This is just a backport of #1149 plus chaneglog update.

More maintenance backports.

---

setup.py

Pyface 7.4.2 release

---

setup.py

Post release version bump 7.4.3

---

setup.py

Add extra Python versions to metadata

---

.github/workflows/test-with-edm.yml
docs/source/overview.rst
etstool.py
pyface/base_toolkit.py
pyface/tests/test_color_dialog.py
pyface/tests/test_font_dialog.py
pyface/ui/qt4/action/action_item.py
pyface/ui/qt4/code_editor/gutters.py
pyface/ui/qt4/directory_dialog.py
pyface/ui/qt4/file_dialog.py
pyface/ui/qt4/util/event_loop_helper.py
pyface/ui/qt4/util/tests/test_gui_test_assistant.py
pyface/wx/shell.py
setup.py

This is the backport PR for 7.4.3 bugfixes.
Fixes #1171.
This is still waiting on:

Backport bugfixes for 7.4.3

---

CHANGES.txt
setup.py

Release PR with Changelog updates.

Release 7.4.3

---

pyface/ui/qt4/util/event_loop_helper.py
pyface/ui/qt4/util/gui_test_assistant.py
pyface/ui/qt4/util/tests/test_gui_test_assistant.py

This backports bugfixes for 7.4.4

Backports for a 7.4.4 release

---

.github/workflows/ets-from-source.yml
.github/workflows/test-with-edm.yml

Currently this:
- fixes CI so it works with current ubuntu-latest on github

More backports for maint/7.4

---

pyface/ui/qt/application_window.py

This PR fixes https://github.com/enthought/pyface/issues/1251, which keeps toolbars from being created due to a copy-and-paste error.

Fix application toolbars
